from django.urls import path

from learning import views

urlpatterns = [
    path("home/", views.LearningHomeView.as_view(), name="learning-home"),
    path("dashboard/", views.LearningDashboardView.as_view(), name="learning-dashboard"),
    path("library/", views.LearningLibraryView.as_view(), name="learning-library"),
    path("library/save/", views.LibrarySaveView.as_view(), name="learning-library-save"),
    path("activity/", views.LearningActivityView.as_view(), name="learning-activity"),
    path("progress/", views.LearningProgressView.as_view(), name="learning-progress"),
    path("tracks/", views.LearningTrackListView.as_view(), name="learning-track-list"),
    path("tracks/<slug:slug>/outline/", views.TrackOutlineView.as_view(), name="learning-track-outline"),
    path("tracks/<slug:slug>/", views.LearningTrackDetailView.as_view(), name="learning-track-detail"),
    path("courses/<slug:slug>/outline/", views.CourseOutlineView.as_view(), name="learning-course-outline"),
    path("courses/<slug:slug>/", views.LearningCourseDetailView.as_view(), name="learning-course-detail"),
    path("lessons/<int:pk>/", views.LearningLessonDetailView.as_view(), name="learning-lesson-detail"),
    path("practice/", views.PracticeSetListView.as_view(), name="learning-practice-list"),
    path("practice/review/", views.PracticeReviewView.as_view(), name="learning-practice-review"),
    path("practice/<int:pk>/", views.PracticeSetDetailView.as_view(), name="learning-practice-detail"),
    path("practice/<int:pk>/submit/", views.PracticeSubmitView.as_view(), name="learning-practice-submit"),
    path("assessments/", views.AssessmentListView.as_view(), name="learning-assessment-list"),
    path("assessments/results/", views.AssessmentResultsView.as_view(), name="learning-assessment-results"),
    path("assessments/<slug:slug>/", views.AssessmentDetailView.as_view(), name="learning-assessment-detail"),
    path("assessments/<slug:slug>/submit/", views.AssessmentSubmitView.as_view(), name="learning-assessment-submit"),
    path("resources/", views.LearningResourceListView.as_view(), name="learning-resource-list"),
    path("resources/<int:pk>/", views.LearningResourceDetailView.as_view(), name="learning-resource-detail"),
    path("my-progress/", views.MyProgressView.as_view(), name="learning-my-progress"),
    path("lessons/<int:pk>/start/", views.LessonStartView.as_view(), name="learning-lesson-start"),
    path("lessons/<int:pk>/complete/", views.LessonCompleteView.as_view(), name="learning-lesson-complete"),
    path(
        "lessons/<int:pk>/complete-with-action/",
        views.LessonCompleteWithActionView.as_view(),
        name="learning-lesson-complete-with-action",
    ),
    path("quiz/<int:pk>/submit/", views.QuizSubmitView.as_view(), name="learning-quiz-submit"),
    path("flashcards/<int:pk>/review/", views.FlashcardReviewView.as_view(), name="learning-flashcard-review"),
    path("xp/", views.XPView.as_view(), name="learning-xp"),
    path("badges/", views.BadgeView.as_view(), name="learning-badges"),
    path("streak/", views.StreakView.as_view(), name="learning-streak"),
]
