# Generated by Django 5.2.15 on 2026-06-14 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("source", models.CharField(default="KES", max_length=80)),
                ("target_category", models.CharField(max_length=120)),
                ("risk_preference", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="route_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RouteResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("summary", models.TextField()),
                ("steps", models.JSONField(default=list)),
                ("disclaimers", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "route_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="results", to="planning.routerequest"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimulationRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "simulator_type",
                    models.CharField(
                        choices=[
                            ("mmf", "Money market fund"),
                            ("tbill", "Treasury bill"),
                            ("sacco", "SACCO"),
                            ("global_route", "Global investing route"),
                        ],
                        max_length=32,
                    ),
                ),
                ("inputs", models.JSONField(default=dict)),
                ("outputs", models.JSONField(default=dict)),
                ("disclaimer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentGoal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("target_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["user", "created_at"], name="planning_in_user_id_cecbec_idx")],
            },
        ),
        migrations.AddIndex(
            model_name="routerequest",
            index=models.Index(fields=["user", "created_at"], name="planning_ro_user_id_4a26e9_idx"),
        ),
        migrations.AddIndex(
            model_name="routerequest",
            index=models.Index(fields=["target_category", "created_at"], name="planning_ro_target__d01b51_idx"),
        ),
        migrations.AddIndex(
            model_name="routeresult",
            index=models.Index(fields=["route_request", "created_at"], name="planning_ro_route_r_9fba02_idx"),
        ),
        migrations.AddIndex(
            model_name="simulationrun",
            index=models.Index(fields=["user", "created_at"], name="planning_si_user_id_801929_idx"),
        ),
        migrations.AddIndex(
            model_name="simulationrun",
            index=models.Index(fields=["simulator_type", "created_at"], name="planning_si_simulat_9859e1_idx"),
        ),
        migrations.AddIndex(
            model_name="simulationrun",
            index=models.Index(fields=["created_at"], name="planning_si_created_89dd9e_idx"),
        ),
    ]
