# Generated by Django 5.2.15 on 2026-06-14 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
        ("planning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationrun",
            name="learning_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="simulation_runs",
                to="learning.learninglesson",
            ),
        ),
        migrations.AddIndex(
            model_name="simulationrun",
            index=models.Index(fields=["learning_lesson", "created_at"], name="planning_si_learnin_dee794_idx"),
        ),
    ]
