# Generated by Django 5.2.15 on 2026-06-16 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_productpassport_freshness_status_and_more"),
        ("knowledge", "0002_datachangeevent"),
        ("planning", "0002_simulationrun_learning_lesson_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("money_market_fund", "Money market fund"),
                            ("fixed_income_fund", "Fixed income fund"),
                            ("balanced_fund", "Balanced fund"),
                            ("equity_fund", "Equity fund"),
                            ("special_fund", "Special fund"),
                            ("treasury_bill", "Treasury bill"),
                            ("treasury_bond", "Treasury bond"),
                            ("infrastructure_bond", "Infrastructure bond"),
                            ("sacco_deposit", "SACCO deposit"),
                            ("sacco_share_capital", "SACCO share capital"),
                            ("fixed_deposit", "Fixed deposit"),
                            ("nse_equity", "NSE equity"),
                            ("reit", "REIT"),
                            ("global_stock_route", "Global stock route"),
                            ("global_etf_route", "Global ETF route"),
                            ("bitcoin_route", "Bitcoin route"),
                            ("land_due_diligence", "Land due diligence"),
                            ("pension_product", "Pension product"),
                            ("other", "Other"),
                        ],
                        max_length=60,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("KES", "KES"),
                            ("USD", "USD"),
                            ("GBP", "GBP"),
                            ("EUR", "EUR"),
                            ("MULTI", "Multi-currency"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="KES",
                        max_length=12,
                    ),
                ),
                ("regulator", models.CharField(blank=True, max_length=120)),
                ("regulator_category", models.CharField(blank=True, max_length=180)),
                ("license_status", models.CharField(blank=True, max_length=120)),
                ("minimum_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("minimum_amount_notes", models.TextField(blank=True)),
                (
                    "liquidity_level",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low"), ("unknown", "Unknown")],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very high"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("typical_use_cases", models.JSONField(blank=True, default=list)),
                ("not_ideal_for", models.JSONField(blank=True, default=list)),
                ("documents_needed", models.JSONField(blank=True, default=list)),
                ("beginner_mistakes", models.JSONField(blank=True, default=list)),
                ("questions_to_ask", models.JSONField(blank=True, default=list)),
                ("public_url", models.URLField(blank=True)),
                (
                    "published_status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "freshness_status",
                    models.CharField(
                        choices=[
                            ("fresh", "Fresh"),
                            ("acceptable", "Acceptable"),
                            ("stale", "Stale"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "source_confidence",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("provider_reported", "Provider reported"),
                            ("editorial", "Editorial"),
                            ("third_party", "Third party"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investment_products",
                        to="catalog.productcategory",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="investment_products",
                        to="catalog.provider",
                    ),
                ),
                (
                    "source_references",
                    models.ManyToManyField(
                        blank=True, related_name="investment_products", to="knowledge.sourcereference"
                    ),
                ),
            ],
            options={
                "ordering": ["category__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductFeeSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("management_fee", "Management fee"),
                            ("trustee_fee", "Trustee fee"),
                            ("custodian_fee", "Custodian fee"),
                            ("withdrawal_fee", "Withdrawal fee"),
                            ("transaction_fee", "Transaction fee"),
                            ("brokerage_fee", "Brokerage fee"),
                            ("platform_fee", "Platform fee"),
                            ("spread", "Spread"),
                            ("tax", "Tax"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("fee_value", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                (
                    "fee_unit",
                    models.CharField(
                        choices=[
                            ("percent", "Percent"),
                            ("kes", "KES"),
                            ("usd", "USD"),
                            ("varies", "Varies"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_schedules",
                        to="planning.investmentproduct",
                    ),
                ),
                (
                    "source_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fee_schedules",
                        to="knowledge.sourcereference",
                    ),
                ),
            ],
            options={
                "ordering": ["product__name", "fee_type"],
            },
        ),
        migrations.CreateModel(
            name="ProductLiquidityRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("withdrawal_timeline", models.CharField(blank=True, max_length=220)),
                ("lock_in_period", models.CharField(blank=True, max_length=180)),
                ("maturity_period_days", models.PositiveIntegerField(blank=True, null=True)),
                ("early_withdrawal_notes", models.TextField(blank=True)),
                (
                    "liquidity_level",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low"), ("unknown", "Unknown")],
                        max_length=32,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidity_rules",
                        to="planning.investmentproduct",
                    ),
                ),
                (
                    "source_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="liquidity_rules",
                        to="knowledge.sourcereference",
                    ),
                ),
            ],
            options={
                "ordering": ["product__name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductRateSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("snapshot_date", models.DateField()),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("effective_annual_yield", "Effective annual yield"),
                            ("annual_yield", "Annual yield"),
                            ("gross_yield", "Gross yield"),
                            ("net_yield", "Net yield"),
                            ("t_bill_average_rate", "T-bill average rate"),
                            ("t_bill_weighted_average_rate", "T-bill weighted average rate"),
                            ("bond_coupon", "Bond coupon"),
                            ("bond_yield", "Bond yield"),
                            ("dividend_yield", "Dividend yield"),
                            ("fixed_deposit_rate", "Fixed deposit rate"),
                            ("estimated_return", "Estimated return"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=60,
                    ),
                ),
                ("rate_value", models.DecimalField(decimal_places=4, max_digits=9)),
                (
                    "rate_period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                            ("auction", "Auction"),
                            ("unknown", "Unknown"),
                        ],
                        default="annual",
                        max_length=32,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("KES", "KES"),
                            ("USD", "USD"),
                            ("GBP", "GBP"),
                            ("EUR", "EUR"),
                            ("MULTI", "Multi-currency"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="KES",
                        max_length=12,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("provider_reported", "Provider reported"),
                            ("editorial", "Editorial"),
                            ("third_party", "Third party"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                ("raw_label", models.CharField(blank=True, max_length=180)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_snapshots",
                        to="planning.investmentproduct",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="knowledge.datasource"
                    ),
                ),
                (
                    "source_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rate_snapshots",
                        to="knowledge.sourcereference",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductSimulationRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("input_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("monthly_topup", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("timeline_months", models.PositiveIntegerField()),
                ("assumed_rate", models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                (
                    "assumed_rate_source",
                    models.CharField(
                        choices=[
                            ("latest_snapshot", "Latest snapshot"),
                            ("manual_user_input", "Manual user input"),
                            ("editorial_default", "Editorial default"),
                            ("scenario", "Scenario"),
                            ("rate_unavailable", "Rate unavailable"),
                        ],
                        default="rate_unavailable",
                        max_length=40,
                    ),
                ),
                ("output", models.JSONField(blank=True, default=dict)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("disclaimer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_simulation_runs",
                        to="catalog.productcategory",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulation_runs",
                        to="planning.investmentproduct",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_simulation_runs",
                        to="catalog.provider",
                    ),
                ),
                (
                    "selected_rate_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulation_runs",
                        to="planning.productratesnapshot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_simulation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SimulationProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("emergency_fund", "Emergency fund"),
                            ("first_investment", "First investment"),
                            ("school_fees", "School fees"),
                            ("land", "Land"),
                            ("business", "Business"),
                            ("retirement", "Retirement"),
                            ("global_exposure", "Global exposure"),
                            ("chama", "Chama"),
                            ("sacco", "SACCO"),
                            ("diaspora", "Diaspora"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=40,
                    ),
                ),
                ("amount_min", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("amount_max", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("timeline_months_min", models.PositiveIntegerField(blank=True, null=True)),
                ("timeline_months_max", models.PositiveIntegerField(blank=True, null=True)),
                ("risk_preference", models.CharField(blank=True, max_length=40)),
                ("liquidity_need", models.CharField(blank=True, max_length=40)),
                (
                    "preferred_currency",
                    models.CharField(
                        choices=[
                            ("KES", "KES"),
                            ("USD", "USD"),
                            ("GBP", "GBP"),
                            ("EUR", "EUR"),
                            ("MULTI", "Multi-currency"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="KES",
                        max_length=12,
                    ),
                ),
                ("user_type", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["goal"], name="planning_si_goal_93a113_idx"),
                    models.Index(fields=["preferred_currency"], name="planning_si_preferr_db8870_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="investmentproduct",
            index=models.Index(fields=["category"], name="planning_in_categor_a07232_idx"),
        ),
        migrations.AddIndex(
            model_name="investmentproduct",
            index=models.Index(fields=["provider"], name="planning_in_provide_d834f2_idx"),
        ),
        migrations.AddIndex(
            model_name="investmentproduct",
            index=models.Index(fields=["product_type"], name="planning_in_product_caa97a_idx"),
        ),
        migrations.AddIndex(
            model_name="investmentproduct",
            index=models.Index(fields=["currency"], name="planning_in_currenc_5210ad_idx"),
        ),
        migrations.AddIndex(
            model_name="investmentproduct",
            index=models.Index(fields=["risk_level"], name="planning_in_risk_le_3e53f2_idx"),
        ),
        migrations.AddIndex(
            model_name="investmentproduct",
            index=models.Index(fields=["liquidity_level"], name="planning_in_liquidi_2aec42_idx"),
        ),
        migrations.AddIndex(
            model_name="investmentproduct",
            index=models.Index(fields=["freshness_status"], name="planning_in_freshne_4447f8_idx"),
        ),
        migrations.AddIndex(
            model_name="investmentproduct",
            index=models.Index(fields=["source_confidence"], name="planning_in_source__bacf3b_idx"),
        ),
        migrations.AddIndex(
            model_name="investmentproduct",
            index=models.Index(fields=["published_status"], name="planning_in_publish_2589f1_idx"),
        ),
        migrations.AddIndex(
            model_name="investmentproduct",
            index=models.Index(fields=["updated_at"], name="planning_in_updated_0eb16d_idx"),
        ),
        migrations.AddIndex(
            model_name="productfeeschedule",
            index=models.Index(fields=["product", "is_current"], name="planning_pr_product_4d8501_idx"),
        ),
        migrations.AddIndex(
            model_name="productliquidityrule",
            index=models.Index(fields=["product"], name="planning_pr_product_fdf927_idx"),
        ),
        migrations.AddIndex(
            model_name="productliquidityrule",
            index=models.Index(fields=["product", "liquidity_level"], name="planning_pr_product_89ece4_idx"),
        ),
        migrations.AddIndex(
            model_name="productratesnapshot",
            index=models.Index(fields=["product", "snapshot_date"], name="planning_pr_product_ba057e_idx"),
        ),
        migrations.AddIndex(
            model_name="productratesnapshot",
            index=models.Index(fields=["product", "is_current"], name="planning_pr_product_78b3ec_idx"),
        ),
        migrations.AddIndex(
            model_name="productratesnapshot",
            index=models.Index(fields=["rate_type"], name="planning_pr_rate_ty_4a6525_idx"),
        ),
        migrations.AddIndex(
            model_name="productratesnapshot",
            index=models.Index(fields=["is_current"], name="planning_pr_is_curr_4371cb_idx"),
        ),
        migrations.AddIndex(
            model_name="productsimulationrun",
            index=models.Index(fields=["user", "created_at"], name="planning_pr_user_id_c9d0ee_idx"),
        ),
        migrations.AddIndex(
            model_name="productsimulationrun",
            index=models.Index(fields=["product", "created_at"], name="planning_pr_product_0f43b5_idx"),
        ),
        migrations.AddIndex(
            model_name="productsimulationrun",
            index=models.Index(fields=["category", "created_at"], name="planning_pr_categor_772219_idx"),
        ),
        migrations.AddIndex(
            model_name="productsimulationrun",
            index=models.Index(fields=["provider", "created_at"], name="planning_pr_provide_b9f94b_idx"),
        ),
    ]
