# Generated by Django 5.2.15 on 2026-06-16 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_datachangeevent'),
        ('planning', '0003_investmentproduct_productfeeschedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StagedProductUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=180)),
                ('product_name', models.CharField(max_length=180)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('proposed_changes', models.JSONField(default=dict)),
                ('parser_confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=32)),
                ('review_status', models.CharField(choices=[('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_approved', 'Auto approved')], default='needs_review', max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ingestion_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_product_updates', to='knowledge.dataingestionrun')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_updates', to='planning.investmentproduct')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_product_updates', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_product_updates', to='knowledge.datasource')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['review_status', 'created_at'], name='planning_st_review__a00da5_idx'), models.Index(fields=['product', 'created_at'], name='planning_st_product_9a4e5c_idx'), models.Index(fields=['source', 'created_at'], name='planning_st_source__e15808_idx')],
            },
        ),
    ]
