# Generated by Django 5.2.15 on 2026-06-17 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_stagedproductupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualSimulationPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My what-if portfolio', max_length=160)),
                ('starting_virtual_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(choices=[('KES', 'KES'), ('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR'), ('MULTI', 'Multi-currency'), ('UNKNOWN', 'Unknown')], default='KES', max_length=12)),
                ('goal', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualSimulationPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_amount_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rate_mode', models.CharField(default='neutral_scenario', max_length=40)),
                ('custom_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('timeline_months', models.PositiveIntegerField(default=12)),
                ('assumptions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='planning.virtualsimulationportfolio')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_positions', to='planning.investmentproduct')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualSimulationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('estimated_growth', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='planning.virtualsimulationportfolio')),
            ],
            options={
                'ordering': ['-snapshot_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='virtualsimulationportfolio',
            index=models.Index(fields=['user', 'created_at'], name='planning_vi_user_id_eba054_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualsimulationposition',
            index=models.Index(fields=['portfolio', 'created_at'], name='planning_vi_portfol_8cf6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualsimulationsnapshot',
            index=models.Index(fields=['portfolio', 'snapshot_date'], name='planning_vi_portfol_ac80b6_idx'),
        ),
    ]
