# Generated by Django 5.2.15 on 2026-06-17 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_provider_provider_type_provider_scheme_name_and_more'),
        ('knowledge', '0002_datachangeevent'),
        ('planning', '0005_virtual_simulation_portfolio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproduct',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='investmentproduct',
            name='product_type',
            field=models.CharField(choices=[('money_market_fund', 'Money market fund'), ('fixed_income_fund', 'Fixed income fund'), ('bond_fund', 'Bond fund'), ('balanced_fund', 'Balanced fund'), ('equity_fund', 'Equity fund'), ('enhanced_yield_fund', 'Enhanced yield fund'), ('wealth_fund', 'Wealth fund'), ('shariah_fund', 'Shariah fund'), ('special_fund', 'Special fund'), ('multi_asset_fund', 'Multi-asset fund'), ('alternative_investment_fund', 'Alternative investment fund'), ('reit', 'REIT'), ('treasury_bill', 'Treasury bill'), ('treasury_bond', 'Treasury bond'), ('infrastructure_bond', 'Infrastructure bond'), ('sacco_deposit', 'SACCO deposit'), ('sacco_share_capital', 'SACCO share capital'), ('fixed_deposit', 'Fixed deposit'), ('nse_equity', 'NSE equity'), ('nse_share_route', 'NSE share route'), ('cds_account_route', 'CDS account route'), ('global_stock_route', 'Global stock route'), ('global_etf_route', 'Global ETF route'), ('pension_product', 'Pension product'), ('insurance_linked_investment', 'Insurance-linked investment'), ('bitcoin_route', 'Bitcoin route'), ('bitcoin_crypto_risk_route', 'Bitcoin/crypto risk route'), ('land_due_diligence', 'Land due diligence'), ('other', 'Other')], max_length=60),
        ),
        migrations.CreateModel(
            name='ProductCatalogImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('import_type', models.CharField(choices=[('official_page_parse', 'Official page parse'), ('provider_page_parse', 'Provider page parse'), ('csv', 'CSV'), ('manual_editorial', 'Manual editorial'), ('backfill', 'Backfill')], default='manual_editorial', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('partial', 'Partial'), ('needs_review', 'Needs review')], default='pending', max_length=32)),
                ('records_seen', models.PositiveIntegerField(default=0)),
                ('providers_created', models.PositiveIntegerField(default=0)),
                ('providers_updated', models.PositiveIntegerField(default=0)),
                ('products_created', models.PositiveIntegerField(default=0)),
                ('products_updated', models.PositiveIntegerField(default=0)),
                ('products_needing_review', models.PositiveIntegerField(default=0)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_import_batches', to='knowledge.datasource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StagedInvestmentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=200)),
                ('scheme_name', models.CharField(blank=True, max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('product_type', models.CharField(blank=True, max_length=60)),
                ('currency', models.CharField(default='UNKNOWN', max_length=12)),
                ('normalized_payload', models.JSONField(blank=True, default=dict)),
                ('source_url', models.URLField(blank=True)),
                ('source_confidence', models.CharField(default='editorial', max_length=32)),
                ('parser_confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=32)),
                ('review_status', models.CharField(choices=[('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_approved', 'Auto approved')], default='needs_review', max_length=32)),
                ('proposed_changes', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_products', to='planning.productcatalogimportbatch')),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_imports', to='planning.investmentproduct')),
                ('matched_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_investment_products', to='catalog.provider')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_staged_products', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_investment_products', to='knowledge.datasource')),
                ('source_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_investment_products', to='knowledge.sourcerecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productcatalogimportbatch',
            index=models.Index(fields=['status', 'created_at'], name='planning_pr_status_17e312_idx'),
        ),
        migrations.AddIndex(
            model_name='productcatalogimportbatch',
            index=models.Index(fields=['import_type', 'created_at'], name='planning_pr_import__51c438_idx'),
        ),
        migrations.AddIndex(
            model_name='stagedinvestmentproduct',
            index=models.Index(fields=['batch', 'review_status'], name='planning_st_batch_i_20f905_idx'),
        ),
        migrations.AddIndex(
            model_name='stagedinvestmentproduct',
            index=models.Index(fields=['review_status', 'created_at'], name='planning_st_review__e5ffdd_idx'),
        ),
        migrations.AddIndex(
            model_name='stagedinvestmentproduct',
            index=models.Index(fields=['provider_name', 'product_name'], name='planning_st_provide_3026a2_idx'),
        ),
    ]
