# Generated by Django 5.2.15 on 2026-06-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_investmentproduct_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproduct',
            name='audited_report_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='investmentproduct',
            name='dividend_rate_latest',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='investmentproduct',
            name='interest_on_deposits_latest',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='investmentproduct',
            name='loan_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='investmentproduct',
            name='management_fee_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='investmentproduct',
            name='membership_eligibility',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='investmentproduct',
            name='minimum_shares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='investmentproduct',
            name='minimum_topup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='investmentproduct',
            name='mpesa_paybill_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentproduct',
            name='mpesa_paybill_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='investmentproduct',
            name='sasra_status',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='investmentproduct',
            name='withdrawal_timeline',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='investmentproduct',
            name='withholding_tax_rate',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AddField(
            model_name='investmentproduct',
            name='yield_type',
            field=models.CharField(choices=[('gross', 'Gross'), ('net_of_management_fee', 'Net of management fee'), ('net_after_tax', 'Net after tax'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
    ]
