# Generated by Django 5.2.15 on 2026-06-14 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-app"),
                            ("email", "Email"),
                            ("push", "Push"),
                            ("sms_placeholder", "SMS placeholder"),
                        ],
                        default="in_app",
                        max_length=32,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("payment_successful", "Payment successful"),
                            ("payment_failed", "Payment failed"),
                            ("premium_activated", "Premium activated"),
                            ("pack_unlocked", "Pack unlocked"),
                            ("professional_responded", "Professional responded"),
                            ("consultation_paid", "Consultation paid"),
                            ("data_grant_expiring", "Data grant expiring"),
                            ("journal_review_reminder", "Journal review reminder"),
                            ("beta_feedback_received", "Beta feedback received"),
                        ],
                        max_length=64,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("unread", "Unread"), ("read", "Read"), ("archived", "Archived")],
                        default="unread",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "status", "created_at"], name="notificatio_user_id_cd4f27_idx"),
                    models.Index(fields=["type", "created_at"], name="notificatio_type_8e213d_idx"),
                ],
            },
        ),
    ]
