# Generated by Django 5.2.15 on 2026-06-17 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("journal", "0003_journalentry_learning_course_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LandOpportunity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("location_text", models.CharField(max_length=255)),
                ("county", models.CharField(blank=True, max_length=120)),
                ("area_or_town", models.CharField(blank=True, max_length=160)),
                ("asking_price", models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ("deposit_requested", models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ("plot_size", models.CharField(blank=True, max_length=120)),
                (
                    "seller_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("company", "Company"),
                            ("agent", "Agent"),
                            ("chama", "Chama"),
                            ("family_member", "Family member"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "title_status",
                    models.CharField(
                        choices=[
                            ("title_seen", "Title seen"),
                            ("title_not_seen", "Title not seen"),
                            ("mother_title", "Mother title"),
                            ("allotment_letter", "Allotment letter"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "intended_use",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("agricultural", "Agricultural"),
                            ("commercial", "Commercial"),
                            ("speculation", "Speculation"),
                            ("chama_project", "Chama project"),
                            ("diaspora_investment", "Diaspora investment"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "decision_stage",
                    models.CharField(
                        choices=[
                            ("browsing", "Browsing"),
                            ("considering", "Considering"),
                            ("before_deposit", "Before deposit"),
                            ("deposit_paid", "Deposit paid"),
                            ("lawyer_review", "Lawyer review"),
                            ("abandoned", "Abandoned"),
                            ("completed", "Completed"),
                        ],
                        default="considering",
                        max_length=32,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very high"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "privacy_mode",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("shared_with_professional", "Shared with professional"),
                            ("shared_with_chama", "Shared with chama"),
                        ],
                        default="private",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="land_opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LandDueDiligenceItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_key", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("requested", "Requested"),
                            ("received", "Received"),
                            ("verified_by_user", "Verified by user"),
                            ("reviewed_by_professional", "Reviewed by professional"),
                            ("not_applicable", "Not applicable"),
                            ("failed", "Failed"),
                        ],
                        default="not_started",
                        max_length=40,
                    ),
                ),
                (
                    "importance",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "professional_type_needed",
                    models.CharField(
                        choices=[
                            ("lawyer", "Lawyer"),
                            ("surveyor", "Surveyor"),
                            ("valuer", "Valuer"),
                            ("land_agent", "Land agent"),
                            ("tax", "Tax"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("source_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "land_opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="due_diligence_items",
                        to="land.landopportunity",
                    ),
                ),
            ],
            options={
                "ordering": ["land_opportunity", "id"],
            },
        ),
        migrations.CreateModel(
            name="LandDocumentRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("title_copy", "Title copy"),
                            ("search_result", "Search result"),
                            ("seller_id", "Seller ID"),
                            ("company_documents", "Company documents"),
                            ("sale_agreement", "Sale agreement"),
                            ("survey_map", "Survey map"),
                            ("mutation_form", "Mutation form"),
                            ("consent", "Consent"),
                            ("rates_rent_clearance", "Rates/rent clearance"),
                            ("payment_receipt", "Payment receipt"),
                            ("site_visit_photo", "Site visit photo"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="land_documents/")),
                ("notes", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("shared_with_professional", "Shared with professional"),
                            ("shared_with_chama", "Shared with chama"),
                        ],
                        default="private",
                        max_length=40,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "land_opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="land.landopportunity"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LandDecisionJournalLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="land_links",
                        to="journal.journalentry",
                    ),
                ),
                (
                    "land_opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_links",
                        to="land.landopportunity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LandRiskFlag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "flag_type",
                    models.CharField(
                        choices=[
                            ("deposit_pressure", "Deposit pressure"),
                            ("no_title_seen", "No title seen"),
                            ("seller_mismatch", "Seller mismatch"),
                            ("unclear_boundaries", "Unclear boundaries"),
                            ("no_lawyer", "No lawyer"),
                            ("no_search_done", "No search done"),
                            ("unrealistic_appreciation_claim", "Unrealistic appreciation claim"),
                            ("unclear_company", "Unclear company"),
                            ("missing_documents", "Missing documents"),
                            ("group_pressure", "Group pressure"),
                            ("diaspora_proxy_risk", "Diaspora proxy risk"),
                            ("other", "Other"),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("info", "Info"), ("warning", "Warning"), ("high", "High"), ("critical", "Critical")],
                        default="warning",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("suggested_action", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "land_opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_flags",
                        to="land.landopportunity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="landopportunity",
            index=models.Index(fields=["user", "created_at"], name="land_landop_user_id_caf9d9_idx"),
        ),
        migrations.AddIndex(
            model_name="landopportunity",
            index=models.Index(fields=["decision_stage", "created_at"], name="land_landop_decisio_590a93_idx"),
        ),
        migrations.AddIndex(
            model_name="landopportunity",
            index=models.Index(fields=["risk_level"], name="land_landop_risk_le_27cf04_idx"),
        ),
        migrations.AddIndex(
            model_name="landduediligenceitem",
            index=models.Index(fields=["land_opportunity", "status"], name="land_landdu_land_op_226bff_idx"),
        ),
        migrations.AddIndex(
            model_name="landduediligenceitem",
            index=models.Index(fields=["importance"], name="land_landdu_importa_29b74e_idx"),
        ),
        migrations.AddConstraint(
            model_name="landduediligenceitem",
            constraint=models.UniqueConstraint(fields=("land_opportunity", "item_key"), name="uniq_land_item_key"),
        ),
        migrations.AddIndex(
            model_name="landdocumentrecord",
            index=models.Index(fields=["land_opportunity", "created_at"], name="land_landdo_land_op_c7e758_idx"),
        ),
        migrations.AddIndex(
            model_name="landdocumentrecord",
            index=models.Index(fields=["document_type"], name="land_landdo_documen_67bb4d_idx"),
        ),
        migrations.AddIndex(
            model_name="landdocumentrecord",
            index=models.Index(fields=["visibility"], name="land_landdo_visibil_ecfdce_idx"),
        ),
        migrations.AddIndex(
            model_name="landdecisionjournallink",
            index=models.Index(fields=["land_opportunity", "created_at"], name="land_landde_land_op_2c88be_idx"),
        ),
        migrations.AddIndex(
            model_name="landriskflag",
            index=models.Index(fields=["land_opportunity", "created_at"], name="land_landri_land_op_bc9c38_idx"),
        ),
        migrations.AddIndex(
            model_name="landriskflag",
            index=models.Index(fields=["severity"], name="land_landri_severit_615a95_idx"),
        ),
    ]
