# Generated by Django 5.2.15 on 2026-06-21 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandCountyMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('region', models.CharField(max_length=60)),
                ('tier', models.CharField(choices=[('Prime', 'Prime'), ('Hotspot', 'Hotspot'), ('Stable', 'Stable'), ('Emerging', 'Emerging')], default='Stable', max_length=12)),
                ('avg_price_per_acre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('appreciation_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rental_yield_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LandSubcountyMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('avg_price_per_acre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('appreciation_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcounties', to='land.landcountymarket')),
            ],
            options={
                'ordering': ['-avg_price_per_acre'],
                'unique_together': {('county', 'name')},
            },
        ),
    ]
