# Generated by Django 5.2.15 on 2026-06-21 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_landcountymarket_landsubcountymarket'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(max_length=80)),
                ('place', models.CharField(max_length=160)),
                ('price_kes', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tag1', models.CharField(blank=True, max_length=60)),
                ('tag2', models.CharField(blank=True, max_length=60)),
                ('advertiser', models.CharField(blank=True, max_length=160)),
                ('listing_url', models.URLField(blank=True)),
                ('is_sponsored', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='land.landcountymarket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['county', 'is_active'], name='land_landli_county__880e4f_idx')],
            },
        ),
    ]
