# Generated by Django 5.2.15 on 2026-06-14 12:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OneOffPurchase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "pack_code",
                    models.CharField(
                        choices=[
                            ("global_investing_pack", "Global investing pack"),
                            ("treasury_bills_pack", "Treasury bills pack"),
                            ("sacco_chama_pack", "SACCO/chama pack"),
                            ("land_due_diligence_literacy_pack", "Land due diligence literacy pack"),
                            ("diaspora_pack", "Diaspora pack"),
                        ],
                        max_length=80,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("pending", "Pending"),
                            ("canceled", "Canceled"),
                            ("refunded", "Refunded"),
                        ],
                        default="completed",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("dev_manual", "Development manual"),
                            ("fake_payment", "Fake payment"),
                            ("future_mpesa", "Future M-Pesa"),
                            ("future_card", "Future card"),
                        ],
                        default="dev_manual",
                        max_length=32,
                    ),
                ),
                ("amount_kes", models.PositiveIntegerField(default=0)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="one_off_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("premium_monthly", "Premium monthly"),
                            ("premium_yearly", "Premium yearly"),
                            ("professional_basic", "Professional basic"),
                            ("professional_pro", "Professional pro"),
                        ],
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "audience",
                    models.CharField(
                        choices=[("consumer", "Consumer"), ("professional", "Professional")], max_length=32
                    ),
                ),
                ("price_kes", models.PositiveIntegerField(default=0)),
                (
                    "billing_period",
                    models.CharField(
                        choices=[("none", "None"), ("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="none",
                        max_length=32,
                    ),
                ),
                ("included_entitlements", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["audience", "price_kes", "code"],
                "indexes": [
                    models.Index(fields=["code"], name="billing_pla_code_927eff_idx"),
                    models.Index(fields=["audience", "is_active"], name="billing_pla_audienc_61dd1d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount_kes", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("source", models.CharField(default="manual_placeholder", max_length=32)),
                ("provider_reference", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "one_off_purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="billing.oneoffpurchase",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="billing.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trialing", "Trialing"),
                            ("canceled", "Canceled"),
                            ("expired", "Expired"),
                            ("manual", "Manual development grant"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("dev_manual", "Development manual"),
                            ("fake_payment", "Fake payment"),
                            ("future_mpesa", "Future M-Pesa"),
                            ("future_card", "Future card"),
                        ],
                        default="dev_manual",
                        max_length=32,
                    ),
                ),
                ("current_period_start", models.DateTimeField(default=django.utils.timezone.now)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="subscriptions", to="billing.plan"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Entitlement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=80)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("subscription", "Subscription"),
                            ("one_off_purchase", "One-off purchase"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                ("source_reference", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["user", "code", "is_active"], name="billing_ent_user_id_3fb0bc_idx"),
                    models.Index(fields=["expires_at"], name="billing_ent_expires_6258ce_idx"),
                ],
                "unique_together": {("user", "code", "source", "source_reference")},
            },
        ),
        migrations.AddIndex(
            model_name="oneoffpurchase",
            index=models.Index(fields=["user", "status"], name="billing_one_user_id_44b7db_idx"),
        ),
        migrations.AddIndex(
            model_name="oneoffpurchase",
            index=models.Index(fields=["pack_code", "status"], name="billing_one_pack_co_e78660_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="oneoffpurchase",
            unique_together={("user", "pack_code", "status")},
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["user", "status"], name="billing_inv_user_id_7efd8f_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status", "created_at"], name="billing_inv_status_bfbaa4_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["user", "status"], name="billing_sub_user_id_fe5b98_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["plan", "status"], name="billing_sub_plan_id_42cf7c_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["current_period_end"], name="billing_sub_current_c59a21_idx"),
        ),
    ]
