# Generated by Django 5.2.15 on 2026-06-14 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0002_consultationresponse_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription"),
                            ("one_off_pack", "One-off pack"),
                            ("professional_consultation", "Professional consultation"),
                        ],
                        max_length=40,
                    ),
                ),
                ("plan_code", models.CharField(blank=True, max_length=64)),
                ("pack_code", models.CharField(blank=True, max_length=80)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="KES", max_length=8)),
                ("phone_number_masked", models.CharField(blank=True, max_length=32)),
                ("provider", models.CharField(choices=[("mpesa", "M-Pesa")], default="mpesa", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("initiated", "Initiated"),
                            ("successful", "Successful"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("provider_checkout_request_id", models.CharField(blank=True, max_length=120)),
                ("provider_merchant_request_id", models.CharField(blank=True, max_length=120)),
                ("provider_receipt", models.CharField(blank=True, max_length=120)),
                ("idempotency_key", models.CharField(max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "consultation_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_intents",
                        to="marketplace.consultationrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=80)),
                ("provider", models.CharField(choices=[("mpesa", "M-Pesa")], default="mpesa", max_length=32)),
                ("safe_payload_summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="payments.paymentintent"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(fields=["user", "status", "created_at"], name="payments_pa_user_id_ec9ee0_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(fields=["provider_checkout_request_id"], name="payments_pa_provide_6ebc70_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(fields=["provider_merchant_request_id"], name="payments_pa_provide_c55e01_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(fields=["status", "expires_at"], name="payments_pa_status_8d1016_idx"),
        ),
        migrations.AddConstraint(
            model_name="paymentintent",
            constraint=models.UniqueConstraint(
                fields=("user", "idempotency_key"), name="unique_payment_intent_idempotency"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentevent",
            index=models.Index(fields=["payment_intent", "created_at"], name="payments_pa_payment_f6eeee_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentevent",
            index=models.Index(fields=["event_type", "created_at"], name="payments_pa_event_t_57cf72_idx"),
        ),
    ]
