# Generated by Django 5.2.15 on 2026-06-14 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")], default="active", max_length=32
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["status"], name="catalog_pro_status_8873b1_idx"),
                    models.Index(fields=["created_at"], name="catalog_pro_created_da8cc9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160, unique=True)),
                ("regulator_category", models.CharField(blank=True, max_length=160)),
                ("website", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")], default="active", max_length=32
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["status"], name="catalog_pro_status_5bc2c2_idx"),
                    models.Index(fields=["created_at"], name="catalog_pro_created_00af73_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductPassport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("regulator_category", models.CharField(blank=True, max_length=180)),
                ("minimum_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                (
                    "liquidity_level",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low"), ("locked", "Locked")],
                        max_length=32,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("very_high", "Very high"),
                        ],
                        max_length=32,
                    ),
                ),
                ("withdrawal_timeline", models.CharField(blank=True, max_length=200)),
                ("fees_summary", models.TextField(blank=True)),
                ("tax_notes", models.TextField(blank=True)),
                ("beginner_mistakes", models.JSONField(blank=True, default=list)),
                ("documents_needed", models.JSONField(blank=True, default=list)),
                ("execution_route_external", models.TextField(blank=True)),
                ("disclosures", models.TextField(blank=True)),
                ("is_sponsored", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_passports",
                        to="catalog.productcategory",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_passports",
                        to="catalog.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["category__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductPassportVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version_number", models.PositiveIntegerField()),
                ("content", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "passport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="catalog.productpassport",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["passport", "created_at"], name="catalog_pro_passpor_ec2369_idx"),
                    models.Index(fields=["status", "created_at"], name="catalog_pro_status_4370a6_idx"),
                ],
                "unique_together": {("passport", "version_number")},
            },
        ),
        migrations.AddIndex(
            model_name="productpassport",
            index=models.Index(fields=["category", "status"], name="catalog_pro_categor_f671e6_idx"),
        ),
        migrations.AddIndex(
            model_name="productpassport",
            index=models.Index(fields=["status", "created_at"], name="catalog_pro_status_e643c2_idx"),
        ),
        migrations.AddIndex(
            model_name="productpassport",
            index=models.Index(fields=["created_at"], name="catalog_pro_created_21106f_idx"),
        ),
    ]
