# Generated by Django 5.2.15 on 2026-06-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpassport",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="productpassport",
            index=models.Index(fields=["category"], name="catalog_pro_categor_2d7439_idx"),
        ),
        migrations.AddIndex(
            model_name="productpassport",
            index=models.Index(fields=["status"], name="catalog_pro_status_43cb63_idx"),
        ),
        migrations.AddIndex(
            model_name="productpassport",
            index=models.Index(fields=["risk_level"], name="catalog_pro_risk_le_52ad96_idx"),
        ),
        migrations.AddIndex(
            model_name="productpassport",
            index=models.Index(fields=["liquidity_level"], name="catalog_pro_liquidi_300527_idx"),
        ),
        migrations.AddIndex(
            model_name="productpassport",
            index=models.Index(fields=["provider"], name="catalog_pro_provide_6405ca_idx"),
        ),
        migrations.AddIndex(
            model_name="productpassport",
            index=models.Index(fields=["updated_at"], name="catalog_pro_updated_9716d8_idx"),
        ),
    ]
