# Generated by Django 5.2.15 on 2026-06-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_productpassport_description_and_more"),
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpassport",
            name="data_freshness",
            field=models.CharField(
                choices=[("fresh", "Fresh"), ("acceptable", "Acceptable"), ("stale", "Stale"), ("unknown", "Unknown")],
                default="unknown",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="productpassport",
            name="editorial_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="productpassport",
            name="last_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productpassport",
            name="public_source_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="productpassport",
            name="published_status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                default="draft",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="productpassport",
            name="regulator_license_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="productpassport",
            name="regulator_status",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="productpassport",
            name="source_references",
            field=models.ManyToManyField(blank=True, related_name="product_passports", to="knowledge.sourcereference"),
        ),
        migrations.AddField(
            model_name="productpassport",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "Unverified"),
                    ("source_verified", "Source verified"),
                    ("manually_reviewed", "Manually reviewed"),
                    ("provider_claimed", "Provider claimed"),
                ],
                default="unverified",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="data_freshness",
            field=models.CharField(
                choices=[("fresh", "Fresh"), ("acceptable", "Acceptable"), ("stale", "Stale"), ("unknown", "Unknown")],
                default="unknown",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="editorial_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="last_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="public_source_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="published_status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                default="draft",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="regulator_license_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="provider",
            name="regulator_status",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="provider",
            name="slug",
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="provider",
            name="source_references",
            field=models.ManyToManyField(blank=True, related_name="catalog_providers", to="knowledge.sourcereference"),
        ),
        migrations.AddField(
            model_name="provider",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "Unverified"),
                    ("source_verified", "Source verified"),
                    ("manually_reviewed", "Manually reviewed"),
                    ("provider_claimed", "Provider claimed"),
                ],
                default="unverified",
                max_length=40,
            ),
        ),
        migrations.AddIndex(
            model_name="productpassport",
            index=models.Index(fields=["category", "published_status"], name="catalog_pro_categor_f330e9_idx"),
        ),
        migrations.AddIndex(
            model_name="productpassport",
            index=models.Index(fields=["published_status"], name="catalog_pro_publish_44ca6e_idx"),
        ),
        migrations.AddIndex(
            model_name="productpassport",
            index=models.Index(fields=["verification_status"], name="catalog_pro_verific_4d48ee_idx"),
        ),
        migrations.AddIndex(
            model_name="productpassport",
            index=models.Index(fields=["data_freshness"], name="catalog_pro_data_fr_e6ad20_idx"),
        ),
        migrations.AddIndex(
            model_name="provider",
            index=models.Index(fields=["slug"], name="catalog_pro_slug_e6a931_idx"),
        ),
        migrations.AddIndex(
            model_name="provider",
            index=models.Index(fields=["published_status"], name="catalog_pro_publish_81c8c7_idx"),
        ),
        migrations.AddIndex(
            model_name="provider",
            index=models.Index(fields=["verification_status"], name="catalog_pro_verific_0be022_idx"),
        ),
        migrations.AddIndex(
            model_name="provider",
            index=models.Index(fields=["data_freshness"], name="catalog_pro_data_fr_d2cfe1_idx"),
        ),
    ]
