# Generated by Django 5.2.15 on 2026-06-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_productpassport_data_freshness_and_more"),
        ("knowledge", "0002_datachangeevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpassport",
            name="freshness_status",
            field=models.CharField(
                choices=[("fresh", "Fresh"), ("acceptable", "Acceptable"), ("stale", "Stale"), ("unknown", "Unknown")],
                default="unknown",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="productpassport",
            name="next_review_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="productpassport",
            index=models.Index(fields=["freshness_status"], name="catalog_pro_freshne_9607a5_idx"),
        ),
        migrations.AddIndex(
            model_name="productpassport",
            index=models.Index(fields=["next_review_due_at"], name="catalog_pro_next_re_a085bb_idx"),
        ),
    ]
