# Generated by Django 5.2.15 on 2026-06-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productpassport_freshness_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(choices=[('fund_manager', 'Fund manager'), ('investment_bank', 'Investment bank'), ('stockbroker', 'Stockbroker'), ('investment_adviser', 'Investment adviser'), ('bank', 'Bank'), ('insurer', 'Insurer'), ('pension_provider', 'Pension provider'), ('sacco', 'SACCO'), ('government_platform', 'Government platform'), ('exchange', 'Exchange'), ('depository', 'Depository'), ('wealth_platform', 'Wealth platform'), ('reit_manager', 'REIT manager'), ('trustee', 'Trustee'), ('custodian', 'Custodian'), ('other', 'Other')], default='other', max_length=40),
        ),
        migrations.AddField(
            model_name='provider',
            name='scheme_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='provider',
            name='source_confidence',
            field=models.CharField(choices=[('official', 'Official'), ('provider_reported', 'Provider reported'), ('editorial', 'Editorial'), ('third_party', 'Third party'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
    ]
