# Generated by Django 5.2.15 on 2026-06-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_provider_provider_type_provider_scheme_name_and_more'),
        ('knowledge', '0002_datachangeevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpassport',
            name='audience',
            field=models.CharField(choices=[('all', 'All users'), ('free', 'Free tier'), ('premium', 'Premium tier')], default='all', max_length=16),
        ),
        migrations.AddIndex(
            model_name='productpassport',
            index=models.Index(fields=['audience'], name='catalog_pro_audienc_f0e9b9_idx'),
        ),
    ]
