# Generated by Django 5.2.15 on 2026-06-14 11:12

from django.db import migrations, models


def ensure_existing_user_profiles(apps, schema_editor):
    user_model = apps.get_model("auth", "User")
    user_profile_model = apps.get_model("accounts", "UserProfile")
    for user in user_model.objects.all():
        role = "admin" if user.is_staff or user.is_superuser else "consumer"
        user_profile_model.objects.get_or_create(user_id=user.id, defaults={"role": role})


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="approximate_investment_range",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_language",
            field=models.CharField(choices=[("en", "English"), ("sw", "Swahili")], default="en", max_length=8),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="privacy_mode_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("first_jobber", "First jobber"),
                    ("professional", "Professional"),
                    ("diaspora", "Diaspora"),
                    ("chama_member", "Chama member"),
                    ("farmer", "Farmer"),
                    ("jua_kali", "Jua kali"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=32,
            ),
        ),
        migrations.RunPython(ensure_existing_user_profiles, migrations.RunPython.noop),
    ]
