# Generated by Django 5.2.15 on 2026-06-14 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("journal.created", "Journal created"),
                            ("portfolio.item_created", "Portfolio item created"),
                            ("risk.scam_check_created", "Scam check created"),
                            ("catalog.product_passport_updated", "Product passport updated"),
                            ("marketplace.consultation_request_created", "Consultation request created"),
                        ],
                        max_length=80,
                    ),
                ),
                ("resource_type", models.CharField(max_length=80)),
                ("resource_id", models.CharField(blank=True, max_length=80)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["actor", "created_at"], name="audit_audit_actor_i_58da28_idx"),
                    models.Index(fields=["event_type", "created_at"], name="audit_audit_event_t_124af2_idx"),
                    models.Index(fields=["created_at"], name="audit_audit_created_7710b7_idx"),
                ],
            },
        ),
    ]
