# Generated by Django 5.2.15 on 2026-06-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("accounts.user_registered", "User registered"),
                    ("accounts.user_logged_in", "User logged in"),
                    ("journal.created", "Journal created"),
                    ("portfolio.item_created", "Portfolio item created"),
                    ("risk.scam_check_created", "Scam check created"),
                    ("catalog.product_passport_updated", "Product passport updated"),
                    ("marketplace.consultation_request_created", "Consultation request created"),
                ],
                max_length=80,
            ),
        ),
    ]
