# Generated by Django 5.2.15 on 2026-06-14 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("goal", models.CharField(blank=True, max_length=180)),
                ("decision", models.TextField()),
                (
                    "amount_display_mode",
                    models.CharField(
                        choices=[("exact", "Exact"), ("rounded", "Rounded"), ("range", "Range"), ("hidden", "Hidden")],
                        default="hidden",
                        max_length=32,
                    ),
                ),
                ("amount_exact", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("amount_range_min", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("amount_range_max", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("reason", models.TextField(blank=True)),
                ("alternatives_considered", models.TextField(blank=True)),
                ("risks_considered", models.TextField(blank=True)),
                ("review_date", models.DateField(blank=True, null=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("shared", "Shared")], default="private", max_length=32
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "created_at"], name="journal_jou_user_id_9e5be0_idx"),
                    models.Index(fields=["created_at"], name="journal_jou_created_41a2c3_idx"),
                ],
            },
        ),
    ]
