# Generated by Django 5.2.15 on 2026-06-14 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_journalentry_version"),
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="learning_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_entries",
                to="learning.learningcourse",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="learning_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_entries",
                to="learning.learninglesson",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="learning_track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_entries",
                to="learning.learningtrack",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["learning_lesson", "created_at"], name="journal_jou_learnin_66fad5_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["learning_course", "created_at"], name="journal_jou_learnin_3d2bdb_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["learning_track", "created_at"], name="journal_jou_learnin_81eb1a_idx"),
        ),
    ]
