# Generated by Django 5.2.15 on 2026-06-14 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("asset_type", models.CharField(max_length=120)),
                ("provider_name", models.CharField(blank=True, max_length=160)),
                (
                    "amount_display_mode",
                    models.CharField(
                        choices=[("exact", "Exact"), ("rounded", "Rounded"), ("range", "Range"), ("hidden", "Hidden")],
                        default="hidden",
                        max_length=32,
                    ),
                ),
                ("amount_exact", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("amount_range_min", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("amount_range_max", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                (
                    "liquidity_level",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low"), ("locked", "Locked")],
                        max_length=32,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("very_high", "Very high"),
                        ],
                        max_length=32,
                    ),
                ),
                ("maturity_date", models.DateField(blank=True, null=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("shared", "Shared")], default="private", max_length=32
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "created_at"], name="portfolio_p_user_id_a841d2_idx"),
                    models.Index(fields=["asset_type"], name="portfolio_p_asset_t_e57fb2_idx"),
                    models.Index(fields=["created_at"], name="portfolio_p_created_3f4a36_idx"),
                ],
            },
        ),
    ]
