# Generated by Django 5.2.15 on 2026-06-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioitem",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
