# Generated by Django 5.2.15 on 2026-06-14 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataGrant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("revoked", "Revoked"), ("expired", "Expired")],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "professional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_grants",
                        to="marketplace.professional",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataAccessLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=120)),
                ("resource_type", models.CharField(max_length=80)),
                ("resource_id", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "professional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_access_logs",
                        to="marketplace.professional",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_grant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="privacy.datagrant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="datagrant",
            index=models.Index(fields=["user", "created_at"], name="privacy_dat_user_id_8e3311_idx"),
        ),
        migrations.AddIndex(
            model_name="datagrant",
            index=models.Index(fields=["professional", "created_at"], name="privacy_dat_profess_369c95_idx"),
        ),
        migrations.AddIndex(
            model_name="datagrant",
            index=models.Index(fields=["status", "expires_at"], name="privacy_dat_status_b383bd_idx"),
        ),
        migrations.AddIndex(
            model_name="dataaccesslog",
            index=models.Index(fields=["user", "created_at"], name="privacy_dat_user_id_3d1342_idx"),
        ),
        migrations.AddIndex(
            model_name="dataaccesslog",
            index=models.Index(fields=["professional", "created_at"], name="privacy_dat_profess_ed1977_idx"),
        ),
        migrations.AddIndex(
            model_name="dataaccesslog",
            index=models.Index(fields=["resource_type", "created_at"], name="privacy_dat_resourc_8447c7_idx"),
        ),
    ]
