# Generated by Django 5.2.15 on 2026-06-14 11:53

from django.conf import settings
from django.db import migrations, models


def populate_professional_grantees(apps, _schema_editor):
    data_grant = apps.get_model("privacy", "DataGrant")
    data_access_log = apps.get_model("privacy", "DataAccessLog")
    for grant in data_grant.objects.exclude(professional_id=None):
        grant.grantee_type = "professional"
        grant.grantee_id = grant.professional_id
        grant.save(update_fields=["grantee_type", "grantee_id"])
    for log in data_access_log.objects.exclude(professional_id=None):
        log.grantee_type = "professional"
        log.grantee_id = log.professional_id
        log.save(update_fields=["grantee_type", "grantee_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
        ("privacy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="datagrant",
            old_name="scope",
            new_name="scopes",
        ),
        migrations.AddField(
            model_name="dataaccesslog",
            name="grantee_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dataaccesslog",
            name="grantee_type",
            field=models.CharField(
                choices=[("professional", "Professional"), ("provider", "Provider"), ("admin", "Admin")],
                default="professional",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="dataaccesslog",
            name="scope",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="datagrant",
            name="grantee_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datagrant",
            name="grantee_type",
            field=models.CharField(
                choices=[("professional", "Professional"), ("provider", "Provider"), ("admin", "Admin")],
                default="professional",
                max_length=32,
            ),
        ),
        migrations.RunPython(populate_professional_grantees, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="dataaccesslog",
            index=models.Index(
                fields=["grantee_type", "grantee_id", "created_at"], name="privacy_dat_grantee_e90982_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datagrant",
            index=models.Index(
                fields=["grantee_type", "grantee_id", "created_at"], name="privacy_dat_grantee_2a9016_idx"
            ),
        ),
    ]
