# Generated by Django 5.2.15 on 2026-06-14 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Professional",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_name", models.CharField(max_length=160)),
                ("regulator_body", models.CharField(blank=True, max_length=160)),
                ("license_number", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("suspended", "Suspended"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="professional_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsultationRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("topic", models.CharField(max_length=180)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("requested", "Requested"), ("reviewing", "Reviewing"), ("closed", "Closed")],
                        default="requested",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultation_requests",
                        to="marketplace.professional",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfessionalVerification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="marketplace.professional",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="professional",
            index=models.Index(fields=["status"], name="marketplace_status_5c0f5f_idx"),
        ),
        migrations.AddIndex(
            model_name="professional",
            index=models.Index(fields=["created_at"], name="marketplace_created_69d383_idx"),
        ),
        migrations.AddIndex(
            model_name="consultationrequest",
            index=models.Index(fields=["user", "created_at"], name="marketplace_user_id_5dc5df_idx"),
        ),
        migrations.AddIndex(
            model_name="consultationrequest",
            index=models.Index(fields=["professional", "created_at"], name="marketplace_profess_52a5f2_idx"),
        ),
        migrations.AddIndex(
            model_name="consultationrequest",
            index=models.Index(fields=["status", "created_at"], name="marketplace_status_2668d0_idx"),
        ),
        migrations.AddIndex(
            model_name="professionalverification",
            index=models.Index(fields=["professional", "created_at"], name="marketplace_profess_bbd9e5_idx"),
        ),
        migrations.AddIndex(
            model_name="professionalverification",
            index=models.Index(fields=["status", "created_at"], name="marketplace_status_b4ac50_idx"),
        ),
    ]
