# Generated by Django 5.2.15 on 2026-06-14 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_marketplace_mvp_fields(apps, _schema_editor):
    professional = apps.get_model("marketplace", "Professional")
    consultation_request = apps.get_model("marketplace", "ConsultationRequest")
    for item in professional.objects.all():
        update_fields = []
        if not item.name:
            item.name = item.display_name
            update_fields.append("name")
        if item.status == "verified" and item.verification_status != "verified":
            item.verification_status = "verified"
            update_fields.append("verification_status")
        if update_fields:
            item.save(update_fields=update_fields)
    for request in consultation_request.objects.all():
        update_fields = []
        if request.professional_id and not request.selected_professional_id:
            request.selected_professional_id = request.professional_id
            update_fields.append("selected_professional")
        if request.notes and not request.user_question:
            request.user_question = request.notes
            update_fields.append("user_question")
        if update_fields:
            request.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
        ("privacy", "0002_rename_scope_datagrant_scopes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("response_text", models.TextField()),
                ("next_steps", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("withdrawn", "Withdrawn")], default="sent", max_length=32
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="amount_display_mode",
            field=models.CharField(
                choices=[("exact", "Exact"), ("rounded", "Rounded"), ("range", "Range"), ("hidden", "Hidden")],
                default="range",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="amount_range_max",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="amount_range_min",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="category",
            field=models.CharField(
                choices=[
                    ("mmf", "MMF"),
                    ("treasury", "Treasury bills/bonds"),
                    ("sacco", "SACCO"),
                    ("chama", "Chama"),
                    ("global_investing", "Global investing"),
                    ("land_literacy", "Land due diligence literacy"),
                    ("tax", "Tax"),
                    ("diaspora", "Diaspora"),
                    ("general_first_investment", "General first investment"),
                ],
                default="general_first_investment",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="data_grant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultation_requests",
                to="privacy.datagrant",
            ),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="preferred_language",
            field=models.CharField(choices=[("en", "English"), ("sw", "Swahili")], default="en", max_length=8),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="risk_preference",
            field=models.CharField(
                choices=[("low", "Low"), ("moderate", "Moderate"), ("high", "High"), ("not_sure", "Not sure")],
                default="not_sure",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="selected_professional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selected_consultation_requests",
                to="marketplace.professional",
            ),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="timeline",
            field=models.CharField(
                choices=[("this_week", "This week"), ("this_month", "This month"), ("flexible", "Flexible")],
                default="flexible",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="user_question",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="professional",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="professional",
            name="chama_support",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="professional",
            name="consultation_fee_range",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="professional",
            name="diaspora_support",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="professional",
            name="disclosures",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="professional",
            name="firm",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="professional",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="professional",
            name="languages",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="professional",
            name="license_category",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="professional",
            name="name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="professional",
            name="specialty",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="professional",
            name="verification_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("verified", "Verified"), ("rejected", "Rejected")],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="consultationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("reviewing", "Reviewing"),
                    ("responded", "Responded"),
                    ("closed", "Closed"),
                ],
                default="requested",
                max_length=32,
            ),
        ),
        migrations.RunPython(populate_marketplace_mvp_fields, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="consultationrequest",
            index=models.Index(fields=["selected_professional", "created_at"], name="marketplace_selecte_5f2f4e_idx"),
        ),
        migrations.AddIndex(
            model_name="consultationrequest",
            index=models.Index(fields=["category", "status", "created_at"], name="marketplace_categor_9b7d9c_idx"),
        ),
        migrations.AddIndex(
            model_name="professional",
            index=models.Index(fields=["verification_status", "is_active"], name="marketplace_verific_d5fbcd_idx"),
        ),
        migrations.AddIndex(
            model_name="professional",
            index=models.Index(fields=["specialty"], name="marketplace_special_536307_idx"),
        ),
        migrations.AddField(
            model_name="consultationresponse",
            name="consultation_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="marketplace.consultationrequest",
            ),
        ),
        migrations.AddField(
            model_name="consultationresponse",
            name="professional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultation_responses",
                to="marketplace.professional",
            ),
        ),
        migrations.AddIndex(
            model_name="consultationresponse",
            index=models.Index(fields=["consultation_request", "created_at"], name="marketplace_consult_d295f8_idx"),
        ),
        migrations.AddIndex(
            model_name="consultationresponse",
            index=models.Index(fields=["professional", "created_at"], name="marketplace_profess_7c0960_idx"),
        ),
    ]
