# Generated by Django 5.2.15 on 2026-06-14 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_consultationresponse_and_more"),
        ("privacy", "0002_rename_scope_datagrant_scopes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationOffer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("proposed_fee", models.DecimalField(decimal_places=2, max_digits=12)),
                ("platform_fee_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("message", models.TextField()),
                ("estimated_duration", models.CharField(max_length=80)),
                ("available_slots_text", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="platform_fee_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="consultationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("professional_responded", "Professional responded"),
                    ("user_selected_professional", "User selected professional"),
                    ("awaiting_payment", "Awaiting payment"),
                    ("paid", "Paid"),
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("requested", "Requested"),
                    ("reviewing", "Reviewing"),
                    ("responded", "Responded"),
                    ("closed", "Closed"),
                ],
                default="requested",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="consultationrequest",
            index=models.Index(fields=["status", "updated_at"], name="marketplace_status_8d68eb_idx"),
        ),
        migrations.AddField(
            model_name="consultationoffer",
            name="consultation_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="offers", to="marketplace.consultationrequest"
            ),
        ),
        migrations.AddField(
            model_name="consultationoffer",
            name="professional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultation_offers",
                to="marketplace.professional",
            ),
        ),
        migrations.AddIndex(
            model_name="consultationoffer",
            index=models.Index(
                fields=["consultation_request", "status", "created_at"], name="marketplace_consult_927c9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultationoffer",
            index=models.Index(fields=["professional", "status", "created_at"], name="marketplace_profess_34dfc1_idx"),
        ),
    ]
