# Generated by Django 5.2.15 on 2026-06-14 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0003_journalentry_learning_course_and_more"),
        ("learning", "0001_initial"),
        ("marketplace", "0003_consultationoffer_consultationrequest_paid_at_and_more"),
        ("privacy", "0002_rename_scope_datagrant_scopes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationrequest",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultation_requests",
                to="journal.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="learning_track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultation_requests",
                to="learning.learningtrack",
            ),
        ),
        migrations.AddIndex(
            model_name="consultationrequest",
            index=models.Index(fields=["learning_track", "created_at"], name="marketplace_learnin_708bf0_idx"),
        ),
        migrations.AddIndex(
            model_name="consultationrequest",
            index=models.Index(fields=["journal_entry", "created_at"], name="marketplace_journal_8ee02c_idx"),
        ),
    ]
