# Generated by Django 5.2.15 on 2026-06-17 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_consultationrequest_journal_entry_and_more"),
        ("planning", "0007_investmentproduct_audited_report_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchedProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("note", models.TextField(blank=True)),
                ("last_seen_rate_value", models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ("last_seen_snapshot_date", models.DateField(blank=True, null=True)),
                ("last_seen_source_confidence", models.CharField(blank=True, max_length=32)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchers",
                        to="planning.investmentproduct",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watched_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "created_at"], name="marketplace_user_id_637924_idx"),
                    models.Index(fields=["product", "created_at"], name="marketplace_product_2c6f26_idx"),
                ],
                "unique_together": {("user", "product")},
            },
        ),
    ]
