# Generated by Django 5.2.15 on 2026-06-14 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("payments_enabled", "Payments enabled"),
                            ("professional_marketplace_enabled", "Professional marketplace enabled"),
                            ("packs_enabled", "Packs enabled"),
                            ("subscriptions_enabled", "Subscriptions enabled"),
                            ("beta_only_mode", "Beta-only mode"),
                        ],
                        max_length=80,
                        unique=True,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="BetaFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("payment_issue", "Payment issue"),
                            ("privacy_question", "Privacy question"),
                            ("professional_review_issue", "Professional review issue"),
                            ("bug_report", "Bug report"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=64,
                    ),
                ),
                ("message", models.TextField()),
                ("screenshot_placeholder", models.CharField(blank=True, max_length=180)),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "New"), ("reviewing", "Reviewing"), ("resolved", "Resolved")],
                        default="new",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["category", "status", "created_at"], name="beta_betafe_categor_f81df4_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="BetaInvite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=80, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("max_uses", models.PositiveIntegerField(default=1)),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_beta_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["code"], name="beta_betain_code_0caf40_idx"),
                    models.Index(fields=["is_active", "expires_at"], name="beta_betain_is_acti_be8dea_idx"),
                ],
            },
        ),
    ]
