# Generated by Django 5.2.15 on 2026-06-14 21:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_productpassport_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningCourse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("estimated_minutes", models.PositiveIntegerField(default=0)),
                ("is_premium", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                        default="draft",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "ordering": ["track__order", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon_key", models.CharField(blank=True, max_length=80)),
                ("criteria_key", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [models.Index(fields=["criteria_key"], name="learning_ba_criteri_48bad5_idx")],
            },
        ),
        migrations.CreateModel(
            name="LearningLesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=200)),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("quiz", "Quiz"),
                            ("flashcard", "Flashcard"),
                            ("simulation", "Simulation"),
                            ("journal_prompt", "Journal prompt"),
                            ("checklist", "Checklist"),
                            ("professional_review_prompt", "Professional review prompt"),
                        ],
                        default="article",
                        max_length=40,
                    ),
                ),
                ("body", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("xp_reward", models.PositiveIntegerField(default=10)),
                ("is_premium", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="learning.learningcourse",
                    ),
                ),
            ],
            options={
                "ordering": ["course__track__order", "course__order", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("front", models.TextField()),
                ("back", models.TextField()),
                ("example", models.TextField(blank=True)),
                ("tag", models.CharField(blank=True, max_length=80)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcards",
                        to="learning.learninglesson",
                    ),
                ),
            ],
            options={
                "ordering": ["lesson__order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LearningTrack",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "level",
                    models.CharField(
                        choices=[("beginner", "Beginner"), ("intermediate", "Intermediate"), ("advanced", "Advanced")],
                        default="beginner",
                        max_length=32,
                    ),
                ),
                (
                    "target_user_type",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("first_jobber", "First jobber"),
                            ("chama_member", "Chama member"),
                            ("diaspora", "Diaspora"),
                            ("farmer", "Farmer"),
                            ("jua_kali", "Jua kali"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=32,
                    ),
                ),
                ("estimated_minutes", models.PositiveIntegerField(default=0)),
                ("is_premium", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "title"],
                "indexes": [
                    models.Index(fields=["status", "order"], name="learning_le_status_96eff4_idx"),
                    models.Index(fields=["level"], name="learning_le_level_3488e0_idx"),
                    models.Index(fields=["target_user_type"], name="learning_le_target__eede92_idx"),
                    models.Index(fields=["is_premium"], name="learning_le_is_prem_5b1dc6_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LearningResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("guide", "Guide"),
                            ("cheat_sheet", "Cheat sheet"),
                            ("tutorial", "Tutorial"),
                            ("glossary", "Glossary"),
                            ("market_brief", "Market brief"),
                            ("checklist", "Checklist"),
                        ],
                        max_length=40,
                    ),
                ),
                ("body", models.TextField()),
                ("is_premium", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "related_product_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_resources",
                        to="catalog.productcategory",
                    ),
                ),
                (
                    "related_track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="learning.learningtrack",
                    ),
                ),
            ],
            options={
                "ordering": ["resource_type", "title"],
            },
        ),
        migrations.AddField(
            model_name="learningcourse",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="courses", to="learning.learningtrack"
            ),
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prompt", models.TextField()),
                ("options", models.JSONField(default=list)),
                ("correct_answer", models.CharField(max_length=240)),
                ("explanation", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                        default="easy",
                        max_length=32,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_questions",
                        to="learning.learninglesson",
                    ),
                ),
            ],
            options={
                "ordering": ["lesson__order", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("awarded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="awards", to="learning.badge"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="badges", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-awarded_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCourseProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("percent_complete", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="learning.learningcourse",
                    ),
                ),
                (
                    "last_lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_for_course_progress",
                        to="learning.learninglesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="UserLessonProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=32,
                    ),
                ),
                ("score", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="learning.learninglesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="UserStreak",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_streak_days", models.PositiveIntegerField(default=0)),
                ("longest_streak_days", models.PositiveIntegerField(default=0)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                ("streak_freezes_available", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_streak",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="XPEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("lesson", "Lesson"),
                            ("quiz", "Quiz"),
                            ("flashcard", "Flashcard"),
                            ("simulation", "Simulation"),
                            ("journal", "Journal"),
                            ("scam_check", "Scam check"),
                            ("streak", "Streak"),
                            ("course", "Course"),
                            ("track", "Track"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_id", models.CharField(blank=True, max_length=80)),
                ("xp_amount", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="learninglesson",
            index=models.Index(fields=["course", "status", "order"], name="learning_le_course__c8a7cb_idx"),
        ),
        migrations.AddIndex(
            model_name="learninglesson",
            index=models.Index(fields=["lesson_type"], name="learning_le_lesson__b205cf_idx"),
        ),
        migrations.AddIndex(
            model_name="learninglesson",
            index=models.Index(fields=["is_premium"], name="learning_le_is_prem_c0ee77_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="learninglesson",
            unique_together={("course", "order"), ("course", "slug")},
        ),
        migrations.AddIndex(
            model_name="flashcard",
            index=models.Index(fields=["lesson", "tag"], name="learning_fl_lesson__d33b01_idx"),
        ),
        migrations.AddIndex(
            model_name="learningresource",
            index=models.Index(fields=["status", "resource_type"], name="learning_le_status_1a7de3_idx"),
        ),
        migrations.AddIndex(
            model_name="learningresource",
            index=models.Index(fields=["related_track", "status"], name="learning_le_related_08e8f5_idx"),
        ),
        migrations.AddIndex(
            model_name="learningresource",
            index=models.Index(fields=["related_product_category", "status"], name="learning_le_related_a1c902_idx"),
        ),
        migrations.AddIndex(
            model_name="learningresource",
            index=models.Index(fields=["is_premium"], name="learning_le_is_prem_4ab07d_idx"),
        ),
        migrations.AddIndex(
            model_name="learningcourse",
            index=models.Index(fields=["track", "status", "order"], name="learning_le_track_i_57af09_idx"),
        ),
        migrations.AddIndex(
            model_name="learningcourse",
            index=models.Index(fields=["is_premium"], name="learning_le_is_prem_d6a440_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="learningcourse",
            unique_together={("track", "order")},
        ),
        migrations.AddIndex(
            model_name="quizquestion",
            index=models.Index(fields=["lesson", "difficulty"], name="learning_qu_lesson__9279bb_idx"),
        ),
        migrations.AddIndex(
            model_name="userbadge",
            index=models.Index(fields=["user", "awarded_at"], name="learning_us_user_id_b1c5c6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="userbadge",
            unique_together={("user", "badge")},
        ),
        migrations.AddIndex(
            model_name="usercourseprogress",
            index=models.Index(fields=["user", "course"], name="learning_us_user_id_7de470_idx"),
        ),
        migrations.AddIndex(
            model_name="usercourseprogress",
            index=models.Index(fields=["completed_at"], name="learning_us_complet_03d718_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="usercourseprogress",
            unique_together={("user", "course")},
        ),
        migrations.AddIndex(
            model_name="userlessonprogress",
            index=models.Index(fields=["user", "status"], name="learning_us_user_id_178695_idx"),
        ),
        migrations.AddIndex(
            model_name="userlessonprogress",
            index=models.Index(fields=["lesson", "status"], name="learning_us_lesson__4e416b_idx"),
        ),
        migrations.AddIndex(
            model_name="userlessonprogress",
            index=models.Index(fields=["completed_at"], name="learning_us_complet_969458_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="userlessonprogress",
            unique_together={("user", "lesson")},
        ),
        migrations.AddIndex(
            model_name="xpevent",
            index=models.Index(fields=["user", "created_at"], name="learning_xp_user_id_6a3525_idx"),
        ),
        migrations.AddIndex(
            model_name="xpevent",
            index=models.Index(fields=["source_type", "source_id"], name="learning_xp_source__08340b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="xpevent",
            unique_together={("user", "source_type", "source_id")},
        ),
    ]
