# ruff: noqa: E501
# Generated by Django 5.2.15 on 2026-06-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_productpassport_data_freshness_and_more"),
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learninglesson",
            name="difficulty",
            field=models.CharField(
                choices=[("beginner", "Beginner"), ("intermediate", "Intermediate"), ("advanced", "Advanced")],
                default="beginner",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="learninglesson",
            name="editorial_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("reviewed", "Reviewed"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="learninglesson",
            name="estimated_minutes",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="learninglesson",
            name="last_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learninglesson",
            name="next_review_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learninglesson",
            name="reviewer_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="learninglesson",
            name="structured_content",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="editorial_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("reviewed", "Reviewed"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="last_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="next_review_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="reviewer_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="structured_content",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="LearningContentSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=220)),
                ("organization", models.CharField(blank=True, max_length=180)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("regulator", "Regulator"),
                            ("exchange", "Exchange"),
                            ("government", "Government"),
                            ("provider", "Provider"),
                            ("editorial", "Editorial"),
                            ("professional_reviewed", "Professional reviewed"),
                        ],
                        default="editorial",
                        max_length=40,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("retrieved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "reliability_level",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("provider", "Provider"),
                            ("editorial", "Editorial"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=40,
                    ),
                ),
            ],
            options={
                "ordering": ["organization", "title"],
                "indexes": [
                    models.Index(fields=["source_type", "reliability_level"], name="learning_le_source__ac57d2_idx"),
                    models.Index(fields=["retrieved_at"], name="learning_le_retriev_15c5e5_idx"),
                ],
                "unique_together": {("title", "organization")},
            },
        ),
        migrations.AddField(
            model_name="learninglesson",
            name="content_sources",
            field=models.ManyToManyField(blank=True, related_name="lessons", to="learning.learningcontentsource"),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="content_sources",
            field=models.ManyToManyField(blank=True, related_name="resources", to="learning.learningcontentsource"),
        ),
        migrations.AddIndex(
            model_name="learninglesson",
            index=models.Index(fields=["editorial_status"], name="learning_le_editori_bf7763_idx"),
        ),
        migrations.AddIndex(
            model_name="learninglesson",
            index=models.Index(fields=["next_review_due_at"], name="learning_le_next_re_511b51_idx"),
        ),
        migrations.AddIndex(
            model_name="learningresource",
            index=models.Index(fields=["editorial_status"], name="learning_le_editori_f1b581_idx"),
        ),
        migrations.AddIndex(
            model_name="learningresource",
            index=models.Index(fields=["next_review_due_at"], name="learning_le_next_re_adb81c_idx"),
        ),
    ]
