# Generated by Django 5.2.15 on 2026-06-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_productpassport_freshness_status_and_more"),
        ("learning", "0002_learninglesson_difficulty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learninglesson",
            name="content_quality_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="learninglesson",
            name="content_warning_flags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="learninglesson",
            name="review_frequency_days",
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name="learninglesson",
            name="source_confidence",
            field=models.CharField(
                choices=[
                    ("official", "Official"),
                    ("provider", "Provider"),
                    ("editorial", "Editorial"),
                    ("mixed", "Mixed"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="content_quality_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="source_confidence",
            field=models.CharField(
                choices=[
                    ("official", "Official"),
                    ("provider", "Provider"),
                    ("editorial", "Editorial"),
                    ("mixed", "Mixed"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="learninglesson",
            index=models.Index(fields=["source_confidence"], name="learning_le_source__99266a_idx"),
        ),
        migrations.AddIndex(
            model_name="learninglesson",
            index=models.Index(fields=["content_quality_score"], name="learning_le_content_1a43ab_idx"),
        ),
        migrations.AddIndex(
            model_name="learningresource",
            index=models.Index(fields=["source_confidence"], name="learning_le_source__895835_idx"),
        ),
        migrations.AddIndex(
            model_name="learningresource",
            index=models.Index(fields=["content_quality_score"], name="learning_le_content_cd2e33_idx"),
        ),
    ]
