# Generated by Django 5.2.15 on 2026-06-16 15:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_learninglesson_content_quality_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('estimated_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=32)),
            ],
            options={
                'ordering': ['course__order', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PracticeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.CharField(max_length=240)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['practice_set', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('review_recent', 'Review recent'), ('weak_area', 'Weak area'), ('scenario_practice', 'Scenario practice'), ('flashcards', 'Flashcards'), ('simulator_practice', 'Simulator practice'), ('scam_red_flag_practice', 'Scam red-flag practice')], default='scenario_practice', max_length=40)),
                ('is_premium', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('xp_reward', models.PositiveIntegerField(default=25)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserAssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('result_label', models.CharField(blank=True, max_length=120)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('passed', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='saved', max_length=32)),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AlterField(
            model_name='learninglesson',
            name='lesson_type',
            field=models.CharField(choices=[('concept', 'Concept'), ('article', 'Article'), ('scenario', 'Scenario'), ('quiz', 'Quiz'), ('flashcard', 'Flashcard'), ('simulation', 'Simulation'), ('simulator', 'Simulator'), ('journal_prompt', 'Journal prompt'), ('checklist', 'Checklist'), ('professional_review_prompt', 'Professional review prompt')], default='article', max_length=40),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('money_profile', 'Money profile'), ('risk_comfort', 'Risk comfort'), ('scam_awareness', 'Scam awareness'), ('liquidity_needs', 'Liquidity needs')], max_length=40)),
                ('scoring', models.CharField(choices=[('knowledge', 'Knowledge (percent correct)'), ('profile', 'Profile (weighted bands)')], default='profile', max_length=20)),
                ('result_bands', models.JSONField(blank=True, default=dict)),
                ('pass_threshold', models.PositiveSmallIntegerField(default=0)),
                ('is_premium', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('xp_reward', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['status', 'order'], name='learning_as_status_5363ca_idx'), models.Index(fields=['kind', 'status'], name='learning_as_kind_7b890d_idx'), models.Index(fields=['is_premium'], name='learning_as_is_prem_24dc8c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.assessment')),
            ],
            options={
                'ordering': ['assessment', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=32)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcard_sets', to='learning.learningtrack')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='flashcard',
            name='flashcard_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='learning.flashcardset'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['flashcard_set'], name='learning_fl_flashca_1cab62_idx'),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning.learningcourse'),
        ),
        migrations.AddField(
            model_name='learninglesson',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='learning.learningmodule'),
        ),
        migrations.AddField(
            model_name='practiceset',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_sets', to='learning.learningtrack'),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='practice_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.practiceset'),
        ),
        migrations.AddField(
            model_name='userassessmentresult',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='learning.assessment'),
        ),
        migrations.AddField(
            model_name='userassessmentresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlibraryitem',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='learning.learningtrack'),
        ),
        migrations.AddField(
            model_name='userlibraryitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['assessment', 'order'], name='learning_as_assessm_cae64f_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcardset',
            index=models.Index(fields=['status'], name='learning_fl_status_018d38_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcardset',
            index=models.Index(fields=['track', 'status'], name='learning_fl_track_i_83f0df_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmodule',
            index=models.Index(fields=['course', 'status', 'order'], name='learning_le_course__fe460a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learningmodule',
            unique_together={('course', 'slug')},
        ),
        migrations.AddIndex(
            model_name='practiceset',
            index=models.Index(fields=['status', 'order'], name='learning_pr_status_815e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='practiceset',
            index=models.Index(fields=['kind', 'status'], name='learning_pr_kind_d54c28_idx'),
        ),
        migrations.AddIndex(
            model_name='practiceset',
            index=models.Index(fields=['track', 'status'], name='learning_pr_track_i_15bedc_idx'),
        ),
        migrations.AddIndex(
            model_name='practiceset',
            index=models.Index(fields=['is_premium'], name='learning_pr_is_prem_e17fca_idx'),
        ),
        migrations.AddIndex(
            model_name='practicequestion',
            index=models.Index(fields=['practice_set', 'order'], name='learning_pr_practic_985510_idx'),
        ),
        migrations.AddIndex(
            model_name='userassessmentresult',
            index=models.Index(fields=['user', 'assessment'], name='learning_us_user_id_27c659_idx'),
        ),
        migrations.AddIndex(
            model_name='userassessmentresult',
            index=models.Index(fields=['completed_at'], name='learning_us_complet_3ef23d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userassessmentresult',
            unique_together={('user', 'assessment')},
        ),
        migrations.AddIndex(
            model_name='userlibraryitem',
            index=models.Index(fields=['user', 'status'], name='learning_us_user_id_0bab82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlibraryitem',
            unique_together={('user', 'track')},
        ),
    ]
