# Generated by Django 5.2.15 on 2026-06-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_learning_product_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpevent',
            name='source_type',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('quiz', 'Quiz'), ('flashcard', 'Flashcard'), ('simulation', 'Simulation'), ('journal', 'Journal'), ('scam_check', 'Scam check'), ('streak', 'Streak'), ('course', 'Course'), ('track', 'Track'), ('practice', 'Practice set'), ('assessment', 'Assessment')], max_length=32),
        ),
    ]
