from datetime import timedelta
from decimal import Decimal

from django.core.management.base import BaseCommand
from django.utils import timezone
from django.utils.text import slugify

from catalog.models import ProductCategory, ProductPassport, ProductPassportVersion, Provider
from planning.models import InvestmentProduct, ProductFeeSchedule, ProductLiquidityRule

CATEGORY_NAMES = [
    "Money Market Funds",
    "Treasury Bills",
    "Treasury Bonds",
    "SACCOs",
    "Chamas",
    "NSE Stocks",
    "US Stocks and ETFs",
    "Land",
    "REITs",
    "Bitcoin and Crypto Risk",
    "Fixed Deposits",
    "Pension Products",
]

SOURCE_URLS = {
    "Bitcoin and Crypto Risk": "https://www.cma.or.ke/",
    "Land": "https://ardhisasa.lands.go.ke/",
    "Money Market Funds": "https://licensees.cma.or.ke/licenses/15/",
    "NSE Stocks": "https://www.nse.co.ke/faqs/",
    "SACCOs": "https://www.sasra.go.ke/regulated-saccos/",
    "Treasury Bills": "https://www.centralbank.go.ke/securities/treasury-bills/",
    "US Stocks and ETFs": "https://www.kra.go.ke/individual/filing-paying/types-of-taxes/capital-gains-tax",
}

PASSPORTS = [
    {
        "name": "Generic MMF",
        "category": "Money Market Funds",
        "minimum_amount": Decimal("1000.00"),
        "description": (
            "A generic money market fund route for learning about liquidity, yield quotes, and provider checks."
        ),
        "liquidity_level": ProductPassport.LiquidityLevel.HIGH,
        "risk_level": ProductPassport.RiskLevel.LOW,
        "withdrawal_timeline": "Often one to three business days, depending on provider processes.",
        "fees_summary": "Fund management and trustee fees may be reflected in quoted yields.",
        "tax_notes": "Withholding tax treatment can change; verify current treatment with a licensed professional.",
    },
    {
        "name": "Generic Treasury Bill via DhowCSD",
        "category": "Treasury Bills",
        "minimum_amount": Decimal("100000.00"),
        "description": (
            "A generic Treasury bill route for learning DhowCSD, auctions, maturities, and settlement steps."
        ),
        "liquidity_level": ProductPassport.LiquidityLevel.MEDIUM,
        "risk_level": ProductPassport.RiskLevel.LOW,
        "withdrawal_timeline": "Held to maturity unless sold through an available secondary route.",
        "fees_summary": "Auction and settlement costs may apply depending on channel.",
        "tax_notes": "Discount interest can be subject to withholding tax.",
    },
    {
        "name": "Generic SACCO Deposits",
        "category": "SACCOs",
        "minimum_amount": Decimal("500.00"),
        "description": (
            "A generic SACCO deposits route for learning membership, share capital, dividends, and liquidity limits."
        ),
        "liquidity_level": ProductPassport.LiquidityLevel.LOW,
        "risk_level": ProductPassport.RiskLevel.MODERATE,
        "withdrawal_timeline": "Withdrawals may require notice or member exit processes.",
        "fees_summary": "Membership fees, share capital rules, and loan-related charges may apply.",
        "tax_notes": "Dividends and rebates can have tax implications.",
    },
    {
        "name": "Generic NSE Shares",
        "category": "NSE Stocks",
        "minimum_amount": Decimal("1000.00"),
        "description": (
            "A generic NSE shares route for learning broker checks, market volatility, fees, and settlement."
        ),
        "liquidity_level": ProductPassport.LiquidityLevel.MEDIUM,
        "risk_level": ProductPassport.RiskLevel.HIGH,
        "withdrawal_timeline": "Settlement timelines depend on broker and market rules.",
        "fees_summary": "Brokerage, statutory, and exchange fees may apply.",
        "tax_notes": "Dividends and capital activity can have tax consequences.",
    },
    {
        "name": "Generic US ETF route",
        "category": "US Stocks and ETFs",
        "minimum_amount": Decimal("5000.00"),
        "description": "A generic global ETF route for learning FX, offshore broker custody, tax, and transfer costs.",
        "liquidity_level": ProductPassport.LiquidityLevel.MEDIUM,
        "risk_level": ProductPassport.RiskLevel.HIGH,
        "withdrawal_timeline": "Depends on offshore broker, FX provider, and bank settlement.",
        "fees_summary": "FX spreads, broker fees, custody fees, and transfer costs may apply.",
        "tax_notes": "Foreign withholding tax and local reporting rules may apply.",
    },
    {
        "name": "Generic Land Due Diligence Checklist",
        "category": "Land",
        "minimum_amount": None,
        "description": (
            "A land due diligence literacy checklist for learning searches, valuation, surveys, and legal review."
        ),
        "liquidity_level": ProductPassport.LiquidityLevel.LOW,
        "risk_level": ProductPassport.RiskLevel.HIGH,
        "withdrawal_timeline": "Illiquid; selling can take months or longer.",
        "fees_summary": "Legal, valuation, search, survey, stamp duty, and transfer costs may apply.",
        "tax_notes": "Land transactions can trigger taxes and statutory fees.",
    },
    {
        "name": "Generic Bitcoin Self-Custody Risk Card",
        "category": "Bitcoin and Crypto Risk",
        "minimum_amount": None,
        "description": "A crypto risk card for learning self-custody, exchange, volatility, and regulatory risks.",
        "liquidity_level": ProductPassport.LiquidityLevel.MEDIUM,
        "risk_level": ProductPassport.RiskLevel.VERY_HIGH,
        "withdrawal_timeline": "Depends on exchange, wallet custody, and network conditions.",
        "fees_summary": "Exchange fees, spreads, withdrawal fees, and network fees may apply.",
        "tax_notes": "Tax treatment and regulatory requirements can change.",
    },
]

SIMULATION_PRODUCTS = [
    {
        "name": "Generic Money Market Fund",
        "category": "Money Market Funds",
        "product_type": InvestmentProduct.ProductType.MONEY_MARKET_FUND,
        "currency": InvestmentProduct.Currency.KES,
        "regulator": "CMA",
        "regulator_category": "Collective Investment Scheme",
        "license_status": "Verify with CMA/provider",
        "minimum_amount": Decimal("1000.00"),
        "liquidity_level": InvestmentProduct.LiquidityLevel.HIGH,
        "risk_level": InvestmentProduct.RiskLevel.LOW,
        "typical_use_cases": ["Emergency buffer learning", "Short-term savings comparison"],
        "not_ideal_for": ["Money needed instantly", "Users who have not checked withdrawal timing"],
        "documents_needed": ["National ID", "KRA PIN", "Bank or mobile money details if opening externally"],
        "beginner_mistakes": ["Choosing by headline yield only", "Ignoring withdrawal cut-off times"],
        "questions_to_ask": ["Is the quoted yield gross or net?", "How long do withdrawals take?"],
        "public_url": SOURCE_URLS["Money Market Funds"],
        "fee_type": ProductFeeSchedule.FeeType.MANAGEMENT_FEE,
        "fee_notes": "Management, trustee, and custodian costs may be reflected in fund disclosures.",
        "withdrawal_timeline": "Often one to three business days, depending on provider processes.",
    },
    {
        "name": "Generic Treasury Bill",
        "category": "Treasury Bills",
        "product_type": InvestmentProduct.ProductType.TREASURY_BILL,
        "currency": InvestmentProduct.Currency.KES,
        "regulator": "CBK",
        "regulator_category": "Government security",
        "license_status": "Issued through official government securities process",
        "minimum_amount": Decimal("100000.00"),
        "liquidity_level": InvestmentProduct.LiquidityLevel.MEDIUM,
        "risk_level": InvestmentProduct.RiskLevel.LOW,
        "typical_use_cases": ["Treasury bill literacy", "Auction and maturity planning"],
        "not_ideal_for": ["Money needed before maturity without understanding secondary routes"],
        "documents_needed": ["National ID", "KRA PIN", "DhowCSD or CDS details where applicable"],
        "beginner_mistakes": ["Confusing purchase price with face value", "Ignoring maturity date"],
        "questions_to_ask": ["Which tenor am I comparing?", "What happens if I need cash before maturity?"],
        "public_url": SOURCE_URLS["Treasury Bills"],
        "fee_type": ProductFeeSchedule.FeeType.OTHER,
        "fee_notes": "Auction, settlement, or channel costs should be verified before acting externally.",
        "withdrawal_timeline": "Typically held to maturity unless a secondary route is available.",
    },
    {
        "name": "Generic Treasury Bond",
        "category": "Treasury Bonds",
        "product_type": InvestmentProduct.ProductType.TREASURY_BOND,
        "currency": InvestmentProduct.Currency.KES,
        "regulator": "CBK",
        "regulator_category": "Government security",
        "license_status": "Issued through official government securities process",
        "minimum_amount": Decimal("50000.00"),
        "liquidity_level": InvestmentProduct.LiquidityLevel.MEDIUM,
        "risk_level": InvestmentProduct.RiskLevel.LOW,
        "typical_use_cases": ["Fixed income literacy", "Coupon and maturity planning"],
        "not_ideal_for": ["Users who need simple short-term liquidity"],
        "documents_needed": ["National ID", "KRA PIN", "DhowCSD or CDS details where applicable"],
        "beginner_mistakes": ["Ignoring price/yield movement", "Assuming coupon equals total return"],
        "questions_to_ask": ["What is the maturity?", "How does selling before maturity work?"],
        "public_url": "https://www.centralbank.go.ke/securities/treasury-bonds/",
        "fee_type": ProductFeeSchedule.FeeType.OTHER,
        "fee_notes": "Verify auction, custody, and secondary market costs with official channels.",
        "withdrawal_timeline": "Maturity can be years away; secondary sale depends on market conditions.",
    },
    {
        "name": "Generic SACCO Deposits",
        "category": "SACCOs",
        "product_type": InvestmentProduct.ProductType.SACCO_DEPOSIT,
        "currency": InvestmentProduct.Currency.KES,
        "regulator": "SASRA",
        "regulator_category": "SACCO",
        "license_status": "Verify SACCO status with SASRA/SACCO documents",
        "minimum_amount": Decimal("500.00"),
        "liquidity_level": InvestmentProduct.LiquidityLevel.LOW,
        "risk_level": InvestmentProduct.RiskLevel.MEDIUM,
        "typical_use_cases": ["SACCO membership literacy", "Savings discipline"],
        "not_ideal_for": ["Emergency money needing instant access"],
        "documents_needed": ["National ID", "KRA PIN", "Membership form", "Nominee details"],
        "beginner_mistakes": ["Assuming deposits are as liquid as a wallet", "Ignoring exit rules"],
        "questions_to_ask": ["How long does withdrawal take?", "What are member exit rules?"],
        "public_url": SOURCE_URLS["SACCOs"],
        "fee_type": ProductFeeSchedule.FeeType.OTHER,
        "fee_notes": "Membership fees, deductions, and withdrawal rules vary by SACCO.",
        "withdrawal_timeline": "Withdrawals may require notice or full member exit processes.",
    },
    {
        "name": "Generic SACCO Share Capital",
        "category": "SACCOs",
        "product_type": InvestmentProduct.ProductType.SACCO_SHARE_CAPITAL,
        "currency": InvestmentProduct.Currency.KES,
        "regulator": "SASRA",
        "regulator_category": "SACCO",
        "license_status": "Verify SACCO status with SASRA/SACCO documents",
        "minimum_amount": Decimal("1000.00"),
        "liquidity_level": InvestmentProduct.LiquidityLevel.LOW,
        "risk_level": InvestmentProduct.RiskLevel.MEDIUM,
        "typical_use_cases": ["Understanding SACCO ownership and dividend language"],
        "not_ideal_for": ["Short-term cash needs"],
        "documents_needed": ["National ID", "KRA PIN", "Membership form"],
        "beginner_mistakes": ["Assuming dividends are guaranteed", "Ignoring transfer/exit restrictions"],
        "questions_to_ask": ["Can share capital be withdrawn?", "How are dividends decided?"],
        "public_url": SOURCE_URLS["SACCOs"],
        "fee_type": ProductFeeSchedule.FeeType.OTHER,
        "fee_notes": "Share-capital rules and transfer terms vary by SACCO.",
        "withdrawal_timeline": "Often locked or transferable only under SACCO rules.",
    },
    {
        "name": "Generic Fixed Deposit",
        "category": "Fixed Deposits",
        "product_type": InvestmentProduct.ProductType.FIXED_DEPOSIT,
        "currency": InvestmentProduct.Currency.KES,
        "regulator": "CBK",
        "regulator_category": "Bank deposit",
        "license_status": "Verify bank/provider status",
        "minimum_amount": Decimal("5000.00"),
        "liquidity_level": InvestmentProduct.LiquidityLevel.LOW,
        "risk_level": InvestmentProduct.RiskLevel.LOW,
        "typical_use_cases": ["Fixed term savings literacy"],
        "not_ideal_for": ["Money needed before maturity"],
        "documents_needed": ["National ID", "KRA PIN", "Bank account details"],
        "beginner_mistakes": ["Ignoring early withdrawal penalty", "Comparing gross rates only"],
        "questions_to_ask": ["What is the penalty for early withdrawal?", "Is rate gross or net?"],
        "public_url": "https://www.centralbank.go.ke/",
        "fee_type": ProductFeeSchedule.FeeType.OTHER,
        "fee_notes": "Verify early withdrawal penalties and tax treatment with the provider.",
        "withdrawal_timeline": "Cash may be locked until maturity or subject to early withdrawal terms.",
    },
    {
        "name": "Generic NSE Share",
        "category": "NSE Stocks",
        "product_type": InvestmentProduct.ProductType.NSE_EQUITY,
        "currency": InvestmentProduct.Currency.KES,
        "regulator": "CMA/NSE",
        "regulator_category": "Listed equity",
        "license_status": "Verify listed status and broker license",
        "minimum_amount": Decimal("1000.00"),
        "liquidity_level": InvestmentProduct.LiquidityLevel.MEDIUM,
        "risk_level": InvestmentProduct.RiskLevel.HIGH,
        "typical_use_cases": ["Listed company literacy", "Broker fee comparison"],
        "not_ideal_for": ["Users unable to tolerate price movement"],
        "documents_needed": ["National ID", "KRA PIN", "CDS account", "Broker account"],
        "beginner_mistakes": ["Treating price movement as predictable", "Ignoring brokerage and taxes"],
        "questions_to_ask": ["What fees apply?", "Can I handle price declines?"],
        "public_url": SOURCE_URLS["NSE Stocks"],
        "fee_type": ProductFeeSchedule.FeeType.BROKERAGE_FEE,
        "fee_notes": "Brokerage and statutory fees should be verified with the broker and NSE/CMA sources.",
        "withdrawal_timeline": "Liquidity depends on market activity, broker settlement, and price.",
    },
    {
        "name": "Generic US ETF Route",
        "category": "US Stocks and ETFs",
        "product_type": InvestmentProduct.ProductType.GLOBAL_ETF_ROUTE,
        "currency": InvestmentProduct.Currency.USD,
        "regulator": "Foreign regulator/provider",
        "regulator_category": "Global investing route",
        "license_status": "Verify platform, custody, FX, and tax route",
        "minimum_amount": Decimal("5000.00"),
        "liquidity_level": InvestmentProduct.LiquidityLevel.MEDIUM,
        "risk_level": InvestmentProduct.RiskLevel.HIGH,
        "typical_use_cases": ["Global exposure literacy", "FX and custody comparison"],
        "not_ideal_for": ["Users who have not checked foreign tax/custody implications"],
        "documents_needed": ["National ID", "KRA PIN", "Platform onboarding documents"],
        "beginner_mistakes": ["Ignoring FX spread", "Assuming foreign tax rules are simple"],
        "questions_to_ask": ["Who custodies the asset?", "What FX, tax, and withdrawal costs apply?"],
        "public_url": SOURCE_URLS["US Stocks and ETFs"],
        "fee_type": ProductFeeSchedule.FeeType.PLATFORM_FEE,
        "fee_notes": "FX spreads, platform fees, custody, tax, and transfer fees may apply.",
        "withdrawal_timeline": "Depends on offshore platform, bank, FX, and settlement processes.",
    },
    {
        "name": "Generic REIT",
        "category": "REITs",
        "product_type": InvestmentProduct.ProductType.REIT,
        "currency": InvestmentProduct.Currency.KES,
        "regulator": "CMA/NSE",
        "regulator_category": "Real estate investment trust",
        "license_status": "Verify listed/licensed status",
        "minimum_amount": Decimal("1000.00"),
        "liquidity_level": InvestmentProduct.LiquidityLevel.MEDIUM,
        "risk_level": InvestmentProduct.RiskLevel.HIGH,
        "typical_use_cases": ["Real estate securities literacy"],
        "not_ideal_for": ["Users seeking direct land ownership"],
        "documents_needed": ["National ID", "KRA PIN", "Broker/CDS details where applicable"],
        "beginner_mistakes": ["Confusing a REIT with owning a plot directly"],
        "questions_to_ask": ["How liquid is trading?", "What distributions and fees apply?"],
        "public_url": "https://www.nse.co.ke/",
        "fee_type": ProductFeeSchedule.FeeType.BROKERAGE_FEE,
        "fee_notes": "Trading and statutory costs may apply through a broker.",
        "withdrawal_timeline": "Liquidity depends on market activity and broker settlement.",
    },
    {
        "name": "Generic Land Due Diligence",
        "category": "Land",
        "product_type": InvestmentProduct.ProductType.LAND_DUE_DILIGENCE,
        "currency": InvestmentProduct.Currency.KES,
        "regulator": "Lands registry/local authorities",
        "regulator_category": "Land due diligence literacy",
        "license_status": "Verify title, survey, seller, and legal process",
        "minimum_amount": None,
        "liquidity_level": InvestmentProduct.LiquidityLevel.LOW,
        "risk_level": InvestmentProduct.RiskLevel.HIGH,
        "typical_use_cases": ["Land process literacy", "Due diligence checklist"],
        "not_ideal_for": ["Users seeking liquid assets"],
        "documents_needed": ["Title search", "Survey map", "Seller ID", "Lawyer review"],
        "beginner_mistakes": ["Paying before title/search verification", "Skipping professional legal review"],
        "questions_to_ask": ["Has the title search been verified?", "Who is reviewing the documents?"],
        "public_url": SOURCE_URLS["Land"],
        "fee_type": ProductFeeSchedule.FeeType.OTHER,
        "fee_notes": "Legal, valuation, survey, transfer, and statutory costs may apply.",
        "withdrawal_timeline": "Land is illiquid; resale can take months or longer.",
    },
    {
        "name": "Generic Bitcoin Route",
        "category": "Bitcoin and Crypto Risk",
        "product_type": InvestmentProduct.ProductType.BITCOIN_ROUTE,
        "currency": InvestmentProduct.Currency.USD,
        "regulator": "Unclear/varies",
        "regulator_category": "Crypto risk literacy",
        "license_status": "Regulatory treatment can change; verify current law",
        "minimum_amount": None,
        "liquidity_level": InvestmentProduct.LiquidityLevel.MEDIUM,
        "risk_level": InvestmentProduct.RiskLevel.VERY_HIGH,
        "typical_use_cases": ["Crypto risk literacy", "Self-custody risk awareness"],
        "not_ideal_for": ["Users who cannot tolerate high volatility or custody mistakes"],
        "documents_needed": ["Exchange/provider disclosures if used externally"],
        "beginner_mistakes": ["Confusing hype with safety", "Ignoring custody and scam risks"],
        "questions_to_ask": ["Who controls the keys?", "What happens if the platform fails?"],
        "public_url": SOURCE_URLS["Bitcoin and Crypto Risk"],
        "fee_type": ProductFeeSchedule.FeeType.SPREAD,
        "fee_notes": "Spreads, network fees, exchange fees, and custody risks may apply.",
        "withdrawal_timeline": "Depends on exchange, wallet, network, and custody process.",
    },
]


class Command(BaseCommand):
    help = "Seed PesaRoute categories and generic product passports."

    def handle(self, *args, **options):
        categories: dict[str, ProductCategory] = {}
        for name in CATEGORY_NAMES:
            category, _created = ProductCategory.objects.update_or_create(
                slug=slugify(name),
                defaults={
                    "name": name,
                    "description": f"Educational overview for {name}.",
                    "status": ProductCategory.Status.ACTIVE,
                },
            )
            categories[name] = category

        provider, _created = Provider.objects.update_or_create(
            name="Generic educational provider",
            defaults={"regulator_category": "Educational placeholder", "status": Provider.Status.ACTIVE},
        )

        for data in PASSPORTS:
            now = timezone.now()
            passport, _created = ProductPassport.objects.update_or_create(
                slug=slugify(data["name"]),
                defaults={
                    "name": data["name"],
                    "category": categories[data["category"]],
                    "provider": provider,
                    "description": data["description"],
                    "regulator_category": data["category"],
                    "minimum_amount": data["minimum_amount"],
                    "liquidity_level": data["liquidity_level"],
                    "risk_level": data["risk_level"],
                    "withdrawal_timeline": data["withdrawal_timeline"],
                    "fees_summary": data["fees_summary"],
                    "tax_notes": data["tax_notes"],
                    "beginner_mistakes": [
                        "Assuming past returns promise future outcomes.",
                        "Skipping provider and regulator checks.",
                    ],
                    "documents_needed": [
                        "National ID",
                        "KRA PIN",
                        "Bank or mobile money details if opening externally",
                    ],
                    "execution_route_external": (
                        "Compare options here, then complete any investment directly with the regulated provider."
                    ),
                    "disclosures": (
                        "Educational simulation only. We do not hold your money, "
                        "execute investments, or promise returns."
                    ),
                    "public_source_url": SOURCE_URLS.get(data["category"], ""),
                    "last_verified_at": now,
                    "next_review_due_at": now + timedelta(days=180),
                    "freshness_status": ProductPassport.FreshnessStatus.FRESH,
                    "data_freshness": ProductPassport.DataFreshness.FRESH,
                    "verification_status": ProductPassport.VerificationStatus.MANUALLY_REVIEWED,
                    "published_status": ProductPassport.Status.PUBLISHED,
                    "is_sponsored": False,
                    "status": ProductPassport.Status.PUBLISHED,
                },
            )
            ProductPassportVersion.objects.update_or_create(
                passport=passport,
                version_number=1,
                defaults={
                    "content": {"seeded": True, "name": passport.name},
                    "status": ProductPassport.Status.PUBLISHED,
                },
            )

        for data in SIMULATION_PRODUCTS:
            now = timezone.now()
            product, _created = InvestmentProduct.objects.update_or_create(
                slug=slugify(data["name"]),
                defaults={
                    "name": data["name"],
                    "category": categories[data["category"]],
                    "provider": provider,
                    "product_type": data["product_type"],
                    "currency": data["currency"],
                    "regulator": data["regulator"],
                    "regulator_category": data["regulator_category"],
                    "license_status": data["license_status"],
                    "minimum_amount": data["minimum_amount"],
                    "minimum_amount_notes": "Verify the current minimum directly with the provider or official source.",
                    "liquidity_level": data["liquidity_level"],
                    "risk_level": data["risk_level"],
                    "typical_use_cases": data["typical_use_cases"],
                    "not_ideal_for": data["not_ideal_for"],
                    "documents_needed": data["documents_needed"],
                    "beginner_mistakes": data["beginner_mistakes"],
                    "questions_to_ask": data["questions_to_ask"],
                    "public_url": data["public_url"],
                    "published_status": InvestmentProduct.PublishedStatus.PUBLISHED,
                    "last_verified_at": now,
                    "freshness_status": InvestmentProduct.FreshnessStatus.ACCEPTABLE,
                    "source_confidence": InvestmentProduct.SourceConfidence.EDITORIAL,
                    "internal_notes": "Generic educational simulation product seeded without live rates.",
                },
            )
            ProductFeeSchedule.objects.update_or_create(
                product=product,
                fee_type=data["fee_type"],
                defaults={
                    "fee_value": None,
                    "fee_unit": ProductFeeSchedule.FeeUnit.VARIES,
                    "notes": data["fee_notes"],
                    "is_current": True,
                },
            )
            ProductLiquidityRule.objects.update_or_create(
                product=product,
                liquidity_level=data["liquidity_level"],
                defaults={
                    "withdrawal_timeline": data["withdrawal_timeline"],
                    "lock_in_period": "",
                    "early_withdrawal_notes": "Verify the current rule with the provider or official source.",
                },
            )

        self.stdout.write(self.style.SUCCESS("Seeded PesaRoute catalog data."))
