# Generated by Django 5.2.15 on 2026-06-14 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("regulator", "Regulator"),
                            ("exchange", "Exchange"),
                            ("government", "Government"),
                            ("provider", "Provider"),
                            ("professional_body", "Professional body"),
                            ("manual_editorial", "Manual editorial"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "authority_level",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("provider_self_reported", "Provider self-reported"),
                            ("editorial", "Editorial"),
                            ("third_party", "Third party"),
                        ],
                        max_length=40,
                    ),
                ),
                ("homepage_url", models.URLField(blank=True)),
                ("data_url", models.URLField(blank=True)),
                ("terms_url", models.URLField(blank=True)),
                ("robots_notes", models.TextField(blank=True)),
                ("license_notes", models.TextField(blank=True)),
                (
                    "update_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                            ("ad_hoc", "Ad hoc"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=40,
                    ),
                ),
                (
                    "parser_strategy",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("csv_import", "CSV import"),
                            ("html_table", "HTML table"),
                            ("pdf", "PDF"),
                            ("api", "API"),
                            ("rss", "RSS"),
                            ("unknown", "Unknown"),
                        ],
                        default="manual",
                        max_length=40,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="knowledge_d_slug_1b2b8a_idx"),
                    models.Index(fields=["source_type", "is_active"], name="knowledge_d_source__a499e9_idx"),
                    models.Index(fields=["authority_level"], name="knowledge_d_authori_a10ff4_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataIngestionRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("scheduled", "Scheduled"),
                            ("backfill", "Backfill"),
                            ("test", "Test"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                            ("needs_review", "Needs review"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("records_seen", models.PositiveIntegerField(default=0)),
                ("records_created", models.PositiveIntegerField(default=0)),
                ("records_updated", models.PositiveIntegerField(default=0)),
                ("records_unchanged", models.PositiveIntegerField(default=0)),
                ("records_failed", models.PositiveIntegerField(default=0)),
                ("error_summary", models.TextField(blank=True)),
                ("raw_snapshot_location", models.CharField(blank=True, max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_runs",
                        to="knowledge.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RawDataSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content_hash", models.CharField(max_length=128)),
                ("content_type", models.CharField(max_length=120)),
                ("fetched_url", models.URLField(blank=True)),
                ("storage_path", models.CharField(blank=True, max_length=500)),
                ("fetched_at", models.DateTimeField()),
                ("byte_size", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raw_snapshots",
                        to="knowledge.dataingestionrun",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_snapshots",
                        to="knowledge.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at"],
            },
        ),
        migrations.CreateModel(
            name="Regulator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180, unique=True)),
                ("abbreviation", models.CharField(max_length=20, unique=True)),
                ("country", models.CharField(default="Kenya", max_length=80)),
                ("website", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["abbreviation"],
                "indexes": [
                    models.Index(fields=["abbreviation"], name="knowledge_r_abbrevi_6c0804_idx"),
                    models.Index(fields=["country"], name="knowledge_r_country_fab89b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="InvestmentProvider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("fund_manager", "Fund manager"),
                            ("stockbroker", "Stockbroker"),
                            ("investment_adviser", "Investment adviser"),
                            ("sacco", "SACCO"),
                            ("bank", "Bank"),
                            ("insurer", "Insurer"),
                            ("pension_provider", "Pension provider"),
                            ("wealth_platform", "Wealth platform"),
                            ("government_platform", "Government platform"),
                            ("exchange", "Exchange"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("license_number", models.CharField(blank=True, max_length=120)),
                ("license_status", models.CharField(blank=True, max_length=120)),
                ("website", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=80)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "published_status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "regulator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="providers",
                        to="knowledge.regulator",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SourceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_record_key", models.CharField(max_length=240)),
                (
                    "source_record_type",
                    models.CharField(
                        choices=[
                            ("provider", "Provider"),
                            ("product", "Product"),
                            ("license", "License"),
                            ("auction_result", "Auction result"),
                            ("listed_company", "Listed company"),
                            ("sacco", "SACCO"),
                            ("pension_service_provider", "Pension service provider"),
                            ("insurance_entity", "Insurance entity"),
                            ("learning_reference", "Learning reference"),
                        ],
                        max_length=60,
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("normalized_payload", models.JSONField(blank=True, default=dict)),
                ("content_hash", models.CharField(max_length=128)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("unchanged", "Unchanged"),
                            ("changed", "Changed"),
                            ("stale", "Stale"),
                            ("retired", "Retired"),
                            ("error", "Error"),
                        ],
                        default="new",
                        max_length=32,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("auto_approved", "Auto approved"),
                            ("needs_review", "Needs review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="needs_review",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_records",
                        to="knowledge.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["source__name", "source_record_key"],
            },
        ),
        migrations.CreateModel(
            name="DataQualityIssue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("missing_field", "Missing field"),
                            ("invalid_format", "Invalid format"),
                            ("duplicate", "Duplicate"),
                            ("stale", "Stale"),
                            ("conflicting_source", "Conflicting source"),
                            ("parse_failure", "Parse failure"),
                            ("permission_warning", "Permission warning"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved"), ("ignored", "Ignored")],
                        default="open",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_issues",
                        to="knowledge.dataingestionrun",
                    ),
                ),
                (
                    "source_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_issues",
                        to="knowledge.sourcerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SourceReference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=240)),
                ("url", models.URLField()),
                ("retrieved_at", models.DateTimeField()),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("citation_label", models.CharField(max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("related_object_type", models.CharField(blank=True, max_length=120)),
                ("related_object_id", models.CharField(blank=True, max_length=80)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="knowledge.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["source__name", "title"],
            },
        ),
        migrations.CreateModel(
            name="SaccoEntity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                (
                    "sacco_type",
                    models.CharField(
                        choices=[
                            ("deposit_taking", "Deposit taking"),
                            ("non_withdrawable_deposit_taking", "Non-withdrawable deposit taking"),
                            ("other", "Other"),
                        ],
                        max_length=60,
                    ),
                ),
                ("sasra_status", models.CharField(max_length=160)),
                ("county", models.CharField(blank=True, max_length=120)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "published_status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "source_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sacco_entities",
                        to="knowledge.sourcereference",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RegulatedEntityStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(max_length=160)),
                ("license_number", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(max_length=120)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("raw_notes", models.TextField(blank=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regulated_statuses",
                        to="knowledge.investmentprovider",
                    ),
                ),
                (
                    "regulator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regulated_entity_statuses",
                        to="knowledge.regulator",
                    ),
                ),
                (
                    "source_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regulated_entity_statuses",
                        to="knowledge.sourcereference",
                    ),
                ),
            ],
            options={
                "ordering": ["provider__name", "regulator__abbreviation"],
            },
        ),
        migrations.CreateModel(
            name="ListedCompany",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("symbol", models.CharField(max_length=20, unique=True)),
                ("isin", models.CharField(blank=True, max_length=60)),
                ("sector", models.CharField(blank=True, max_length=120)),
                ("listing_segment", models.CharField(blank=True, max_length=120)),
                ("website", models.URLField(blank=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "published_status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "source_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listed_companies",
                        to="knowledge.sourcereference",
                    ),
                ),
            ],
            options={
                "ordering": ["symbol"],
            },
        ),
        migrations.AddField(
            model_name="investmentprovider",
            name="source_references",
            field=models.ManyToManyField(
                blank=True, related_name="investment_providers", to="knowledge.sourcereference"
            ),
        ),
        migrations.CreateModel(
            name="InvestmentProductCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160, unique=True)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "risk_level_default",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("very_high", "Very high"),
                        ],
                        default="moderate",
                        max_length=32,
                    ),
                ),
                (
                    "liquidity_level_default",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low"), ("locked", "Locked")],
                        default="medium",
                        max_length=32,
                    ),
                ),
                ("beginner_summary", models.TextField(blank=True)),
                ("regulatory_notes", models.TextField(blank=True)),
                ("typical_minimum_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                (
                    "source_references",
                    models.ManyToManyField(
                        blank=True, related_name="product_categories", to="knowledge.sourcereference"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GovernmentSecurityReference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "security_type",
                    models.CharField(
                        choices=[
                            ("treasury_bill", "Treasury bill"),
                            ("treasury_bond", "Treasury bond"),
                            ("infrastructure_bond", "Infrastructure bond"),
                        ],
                        max_length=40,
                    ),
                ),
                ("tenor_days", models.PositiveIntegerField(blank=True, null=True)),
                ("issue_number", models.CharField(blank=True, max_length=120)),
                ("isin", models.CharField(blank=True, max_length=60)),
                ("auction_date", models.DateField(blank=True, null=True)),
                ("value_date", models.DateField(blank=True, null=True)),
                ("maturity_date", models.DateField(blank=True, null=True)),
                ("average_rate", models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ("accepted_yield", models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ("status", models.CharField(blank=True, max_length=120)),
                (
                    "source_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="government_securities",
                        to="knowledge.sourcereference",
                    ),
                ),
            ],
            options={
                "ordering": ["-auction_date", "security_type"],
            },
        ),
        migrations.AddIndex(
            model_name="dataingestionrun",
            index=models.Index(fields=["source", "started_at"], name="knowledge_d_source__032fb6_idx"),
        ),
        migrations.AddIndex(
            model_name="dataingestionrun",
            index=models.Index(fields=["status", "started_at"], name="knowledge_d_status_952219_idx"),
        ),
        migrations.AddIndex(
            model_name="rawdatasnapshot",
            index=models.Index(fields=["source", "fetched_at"], name="knowledge_r_source__03d6b9_idx"),
        ),
        migrations.AddIndex(
            model_name="rawdatasnapshot",
            index=models.Index(fields=["content_hash"], name="knowledge_r_content_1c0e62_idx"),
        ),
        migrations.AddIndex(
            model_name="sourcerecord",
            index=models.Index(fields=["source", "source_record_key"], name="knowledge_s_source__f14573_idx"),
        ),
        migrations.AddIndex(
            model_name="sourcerecord",
            index=models.Index(fields=["source_record_type"], name="knowledge_s_source__b4722d_idx"),
        ),
        migrations.AddIndex(
            model_name="sourcerecord",
            index=models.Index(fields=["review_status"], name="knowledge_s_review__2a25fe_idx"),
        ),
        migrations.AddIndex(
            model_name="sourcerecord",
            index=models.Index(fields=["status"], name="knowledge_s_status_d9360e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="sourcerecord",
            unique_together={("source", "source_record_key")},
        ),
        migrations.AddIndex(
            model_name="dataqualityissue",
            index=models.Index(fields=["ingestion_run", "created_at"], name="knowledge_d_ingesti_8bb342_idx"),
        ),
        migrations.AddIndex(
            model_name="dataqualityissue",
            index=models.Index(fields=["source_record", "created_at"], name="knowledge_d_source__cb1e62_idx"),
        ),
        migrations.AddIndex(
            model_name="dataqualityissue",
            index=models.Index(fields=["severity", "status"], name="knowledge_d_severit_aef8a5_idx"),
        ),
        migrations.AddIndex(
            model_name="dataqualityissue",
            index=models.Index(fields=["issue_type", "status"], name="knowledge_d_issue_t_7361fe_idx"),
        ),
        migrations.AddIndex(
            model_name="sourcereference",
            index=models.Index(fields=["source", "retrieved_at"], name="knowledge_s_source__e252ff_idx"),
        ),
        migrations.AddIndex(
            model_name="sourcereference",
            index=models.Index(
                fields=["related_object_type", "related_object_id"], name="knowledge_s_related_d5c094_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saccoentity",
            index=models.Index(fields=["name", "sasra_status"], name="knowledge_s_name_d3830b_idx"),
        ),
        migrations.AddIndex(
            model_name="saccoentity",
            index=models.Index(fields=["sacco_type", "sasra_status"], name="knowledge_s_sacco_t_727d2d_idx"),
        ),
        migrations.AddIndex(
            model_name="saccoentity",
            index=models.Index(fields=["published_status"], name="knowledge_s_publish_b7ed08_idx"),
        ),
        migrations.AddIndex(
            model_name="regulatedentitystatus",
            index=models.Index(fields=["provider", "regulator"], name="knowledge_r_provide_0c8858_idx"),
        ),
        migrations.AddIndex(
            model_name="regulatedentitystatus",
            index=models.Index(fields=["category", "status"], name="knowledge_r_categor_73bf3e_idx"),
        ),
        migrations.AddIndex(
            model_name="regulatedentitystatus",
            index=models.Index(fields=["license_number"], name="knowledge_r_license_b67327_idx"),
        ),
        migrations.AddIndex(
            model_name="listedcompany",
            index=models.Index(fields=["symbol"], name="knowledge_l_symbol_87073e_idx"),
        ),
        migrations.AddIndex(
            model_name="listedcompany",
            index=models.Index(fields=["sector"], name="knowledge_l_sector_9075a3_idx"),
        ),
        migrations.AddIndex(
            model_name="listedcompany",
            index=models.Index(fields=["published_status"], name="knowledge_l_publish_878894_idx"),
        ),
        migrations.AddIndex(
            model_name="investmentprovider",
            index=models.Index(fields=["slug"], name="knowledge_i_slug_47810c_idx"),
        ),
        migrations.AddIndex(
            model_name="investmentprovider",
            index=models.Index(fields=["provider_type"], name="knowledge_i_provide_6bfcfa_idx"),
        ),
        migrations.AddIndex(
            model_name="investmentprovider",
            index=models.Index(fields=["regulator"], name="knowledge_i_regulat_53a3a6_idx"),
        ),
        migrations.AddIndex(
            model_name="investmentprovider",
            index=models.Index(fields=["published_status"], name="knowledge_i_publish_bf0949_idx"),
        ),
        migrations.AddIndex(
            model_name="investmentproductcategory",
            index=models.Index(fields=["slug"], name="knowledge_i_slug_fe55dc_idx"),
        ),
        migrations.AddIndex(
            model_name="investmentproductcategory",
            index=models.Index(fields=["risk_level_default"], name="knowledge_i_risk_le_d3f65e_idx"),
        ),
        migrations.AddIndex(
            model_name="investmentproductcategory",
            index=models.Index(fields=["liquidity_level_default"], name="knowledge_i_liquidi_811950_idx"),
        ),
        migrations.AddIndex(
            model_name="governmentsecurityreference",
            index=models.Index(fields=["security_type", "auction_date"], name="knowledge_g_securit_147c2a_idx"),
        ),
        migrations.AddIndex(
            model_name="governmentsecurityreference",
            index=models.Index(fields=["isin"], name="knowledge_g_isin_97562f_idx"),
        ),
        migrations.AddIndex(
            model_name="governmentsecurityreference",
            index=models.Index(fields=["issue_number"], name="knowledge_g_issue_n_6de69b_idx"),
        ),
    ]
