# ruff: noqa: E501
# Generated by Django 5.2.15 on 2026-06-15 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataChangeEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_type", models.CharField(max_length=120)),
                ("object_id", models.CharField(blank=True, max_length=80)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("retired", "Retired"),
                            ("stale", "Stale"),
                            ("source_changed", "Source changed"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=40,
                    ),
                ),
                ("old_value", models.JSONField(blank=True, default=dict)),
                ("new_value", models.JSONField(blank=True, default=dict)),
                ("requires_review", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_events",
                        to="knowledge.dataingestionrun",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_events",
                        to="knowledge.datasource",
                    ),
                ),
                (
                    "source_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_events",
                        to="knowledge.sourcerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["object_type", "object_id"], name="knowledge_d_object__5ccb8c_idx"),
                    models.Index(fields=["change_type", "created_at"], name="knowledge_d_change__0a1ee5_idx"),
                    models.Index(fields=["requires_review", "created_at"], name="knowledge_d_require_ae53c7_idx"),
                    models.Index(fields=["source", "created_at"], name="knowledge_d_source__262977_idx"),
                ],
            },
        ),
    ]
