# Generated by Django 5.2.15 on 2026-06-14 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScamCheck",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prompt_text", models.TextField()),
                ("risk_score", models.PositiveIntegerField()),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("severe", "Severe")],
                        max_length=32,
                    ),
                ),
                ("flags", models.JSONField(default=list)),
                ("questions_to_ask", models.JSONField(default=list)),
                ("disclaimer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scam_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScamFlag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phrase", models.CharField(max_length=160)),
                ("reason", models.TextField()),
                ("weight", models.PositiveIntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scam_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="flag_rows", to="risk.scamcheck"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="scamcheck",
            index=models.Index(fields=["user", "created_at"], name="risk_scamch_user_id_96040b_idx"),
        ),
        migrations.AddIndex(
            model_name="scamcheck",
            index=models.Index(fields=["risk_level", "created_at"], name="risk_scamch_risk_le_20518f_idx"),
        ),
        migrations.AddIndex(
            model_name="scamflag",
            index=models.Index(fields=["scam_check", "created_at"], name="risk_scamfl_scam_ch_bcedd5_idx"),
        ),
    ]
